package com.common.dao;

import com.common.dao.model.T105;
import com.common.dao.model.T105Example;
import com.common.dao.model.T105Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T105Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int countByExample(T105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int deleteByExample(T105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int deleteByPrimaryKey(T105Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int insert(T105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int insertSelective(T105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    List<T105> selectByExample(T105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    T105 selectByPrimaryKey(T105Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByExampleSelective(@Param("record") T105 record, @Param("example") T105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByExample(@Param("record") T105 record, @Param("example") T105Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByPrimaryKeySelective(T105 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T105
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByPrimaryKey(T105 record);
}