package com.common.dao;

import com.common.dao.model.Te11;
import com.common.dao.model.Te11Example;
import com.common.dao.model.Te11Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te11Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int countByExample(Te11Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int deleteByExample(Te11Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int deleteByPrimaryKey(Te11Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int insert(Te11 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int insertSelective(Te11 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    List<Te11> selectByExample(Te11Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    Te11 selectByPrimaryKey(Te11Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int updateByExampleSelective(@Param("record") Te11 record, @Param("example") Te11Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int updateByExample(@Param("record") Te11 record, @Param("example") Te11Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int updateByPrimaryKeySelective(Te11 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE11
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    int updateByPrimaryKey(Te11 record);
}