package com.example.model;

import java.util.Date;

public class UserMaster {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.USER_MASTER.USER_ID
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.USER_MASTER.DEPT_NO
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    private String deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.USER_MASTER.USER_NAME
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.USER_MASTER.CREATED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    private Date createdOn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.USER_MASTER.MODIFIED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    private Date modifiedOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.USER_MASTER.USER_ID
     *
     * @return the value of SYSTEM.USER_MASTER.USER_ID
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.USER_MASTER.USER_ID
     *
     * @param userId the value for SYSTEM.USER_MASTER.USER_ID
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.USER_MASTER.DEPT_NO
     *
     * @return the value of SYSTEM.USER_MASTER.DEPT_NO
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.USER_MASTER.DEPT_NO
     *
     * @param deptNo the value for SYSTEM.USER_MASTER.DEPT_NO
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.USER_MASTER.USER_NAME
     *
     * @return the value of SYSTEM.USER_MASTER.USER_NAME
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.USER_MASTER.USER_NAME
     *
     * @param userName the value for SYSTEM.USER_MASTER.USER_NAME
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.USER_MASTER.CREATED_ON
     *
     * @return the value of SYSTEM.USER_MASTER.CREATED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public Date getCreatedOn() {
        return createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.USER_MASTER.CREATED_ON
     *
     * @param createdOn the value for SYSTEM.USER_MASTER.CREATED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.USER_MASTER.MODIFIED_ON
     *
     * @return the value of SYSTEM.USER_MASTER.MODIFIED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public Date getModifiedOn() {
        return modifiedOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.USER_MASTER.MODIFIED_ON
     *
     * @param modifiedOn the value for SYSTEM.USER_MASTER.MODIFIED_ON
     *
     * @mbggenerated Sun May 08 14:50:17 JST 2016
     */
    public void setModifiedOn(Date modifiedOn) {
        this.modifiedOn = modifiedOn;
    }
}