package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.MSysUserGroup;
import net.newbiz.ebil.system.dao.model.MSysUserGroupExample;
import net.newbiz.ebil.system.dao.model.MSysUserGroupKey;
import org.apache.ibatis.annotations.Param;

public interface MSysUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int countByExample(MSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int deleteByExample(MSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MSysUserGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int insert(MSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int insertSelective(MSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    List<MSysUserGroup> selectByExample(MSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    MSysUserGroup selectByPrimaryKey(MSysUserGroupKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MSysUserGroup record, @Param("example") MSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MSysUserGroup record, @Param("example") MSysUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSysUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSysUserGroup record);
}