package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.MSysGroupRole;
import net.newbiz.ebil.system.dao.model.MSysGroupRoleExample;
import net.newbiz.ebil.system.dao.model.MSysGroupRoleKey;
import org.apache.ibatis.annotations.Param;

public interface MSysGroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int countByExample(MSysGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int deleteByExample(MSysGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MSysGroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int insert(MSysGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int insertSelective(MSysGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    List<MSysGroupRole> selectByExample(MSysGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    MSysGroupRole selectByPrimaryKey(MSysGroupRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MSysGroupRole record, @Param("example") MSysGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MSysGroupRole record, @Param("example") MSysGroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSysGroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_group_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSysGroupRole record);
}