package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.MSysUserRole;
import net.newbiz.ebil.system.dao.model.MSysUserRoleExample;
import net.newbiz.ebil.system.dao.model.MSysUserRoleKey;
import org.apache.ibatis.annotations.Param;

public interface MSysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int countByExample(MSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(MSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MSysUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int insert(MSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int insertSelective(MSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    List<MSysUserRole> selectByExample(MSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    MSysUserRole selectByPrimaryKey(MSysUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MSysUserRole record, @Param("example") MSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MSysUserRole record, @Param("example") MSysUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSysUserRole record);
}