package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.MSysUser;
import net.newbiz.ebil.system.dao.model.MSysUserExample;
import org.apache.ibatis.annotations.Param;

public interface MSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int countByExample(MSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int deleteByExample(MSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int insert(MSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int insertSelective(MSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    List<MSysUser> selectByExample(MSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    MSysUser selectByPrimaryKey(String sysUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MSysUser record, @Param("example") MSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MSysUser record, @Param("example") MSysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSysUser record);
}