package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.MSysRoleAuthority;
import net.newbiz.ebil.system.dao.model.MSysRoleAuthorityExample;
import net.newbiz.ebil.system.dao.model.MSysRoleAuthorityKey;
import org.apache.ibatis.annotations.Param;

public interface MSysRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int countByExample(MSysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int deleteByExample(MSysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(MSysRoleAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int insert(MSysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int insertSelective(MSysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    List<MSysRoleAuthority> selectByExample(MSysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    MSysRoleAuthority selectByPrimaryKey(MSysRoleAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MSysRoleAuthority record, @Param("example") MSysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MSysRoleAuthority record, @Param("example") MSysRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MSysRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_sys_role_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MSysRoleAuthority record);
}