package net.newbiz.ebil.system.dao;

import java.util.List;
import net.newbiz.ebil.system.dao.model.TUserTodo;
import net.newbiz.ebil.system.dao.model.TUserTodoExample;
import org.apache.ibatis.annotations.Param;

public interface TUserTodoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int countByExample(TUserTodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int deleteByExample(TUserTodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userTodoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int insert(TUserTodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int insertSelective(TUserTodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    List<TUserTodo> selectByExample(TUserTodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    TUserTodo selectByPrimaryKey(Integer userTodoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TUserTodo record, @Param("example") TUserTodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TUserTodo record, @Param("example") TUserTodoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TUserTodo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_todo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserTodo record);
}