/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tekuteku_tomotomo' at '16/05/08 10:45' with Gradle 2.9
 *
 * @author tekuteku_tomotomo, @date 16/05/08 10:45
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
