package com.common.dao;

import com.common.dao.model.Te17;
import com.common.dao.model.Te17Example;
import com.common.dao.model.Te17Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te17Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int countByExample(Te17Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int deleteByExample(Te17Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Te17Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int insert(Te17 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int insertSelective(Te17 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    List<Te17> selectByExample(Te17Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    Te17 selectByPrimaryKey(Te17Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Te17 record, @Param("example") Te17Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Te17 record, @Param("example") Te17Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Te17 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE17
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Te17 record);
}