package com.common.dao;

import com.common.dao.model.Te72;
import com.common.dao.model.Te72Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te72Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int countByExample(Te72Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int deleteByExample(Te72Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String te72001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int insert(Te72 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int insertSelective(Te72 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    List<Te72> selectByExample(Te72Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    Te72 selectByPrimaryKey(String te72001);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Te72 record, @Param("example") Te72Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Te72 record, @Param("example") Te72Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Te72 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE72
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Te72 record);
}