package com.common.dao;

import com.common.dao.model.Te79;
import com.common.dao.model.Te79Example;
import com.common.dao.model.Te79Key;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te79Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int countByExample(Te79Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int deleteByExample(Te79Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int deleteByPrimaryKey(Te79Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int insert(Te79 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int insertSelective(Te79 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    List<Te79> selectByExample(Te79Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    Te79 selectByPrimaryKey(Te79Key key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByExampleSelective(@Param("record") Te79 record, @Param("example") Te79Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByExample(@Param("record") Te79 record, @Param("example") Te79Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByPrimaryKeySelective(Te79 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    int updateByPrimaryKey(Te79 record);
}