package com.common.dao;

import com.common.dao.model.Te7a;
import com.common.dao.model.Te7aExample;
import com.common.dao.model.Te7aKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te7aMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int countByExample(Te7aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int deleteByExample(Te7aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Te7aKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int insert(Te7a record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int insertSelective(Te7a record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    List<Te7a> selectByExample(Te7aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    Te7a selectByPrimaryKey(Te7aKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Te7a record, @Param("example") Te7aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Te7a record, @Param("example") Te7aExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Te7a record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Te7a record);
}