package com.common.dao;

import com.common.dao.model.Te7b;
import com.common.dao.model.Te7bExample;
import com.common.dao.model.Te7bKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Te7bMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int countByExample(Te7bExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int deleteByExample(Te7bExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Te7bKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int insert(Te7b record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int insertSelective(Te7b record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    List<Te7b> selectByExample(Te7bExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    Te7b selectByPrimaryKey(Te7bKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Te7b record, @Param("example") Te7bExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Te7b record, @Param("example") Te7bExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Te7b record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Te7b record);
}