package com.common.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class T0a9Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public T0a9Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andT0a9001IsNull() {
            addCriterion("T0A9001 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9001IsNotNull() {
            addCriterion("T0A9001 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9001EqualTo(String value) {
            addCriterion("T0A9001 =", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001NotEqualTo(String value) {
            addCriterion("T0A9001 <>", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001GreaterThan(String value) {
            addCriterion("T0A9001 >", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001GreaterThanOrEqualTo(String value) {
            addCriterion("T0A9001 >=", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001LessThan(String value) {
            addCriterion("T0A9001 <", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001LessThanOrEqualTo(String value) {
            addCriterion("T0A9001 <=", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001Like(String value) {
            addCriterion("T0A9001 like", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001NotLike(String value) {
            addCriterion("T0A9001 not like", value, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001In(List<String> values) {
            addCriterion("T0A9001 in", values, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001NotIn(List<String> values) {
            addCriterion("T0A9001 not in", values, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001Between(String value1, String value2) {
            addCriterion("T0A9001 between", value1, value2, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9001NotBetween(String value1, String value2) {
            addCriterion("T0A9001 not between", value1, value2, "t0a9001");
            return (Criteria) this;
        }

        public Criteria andT0a9002IsNull() {
            addCriterion("T0A9002 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9002IsNotNull() {
            addCriterion("T0A9002 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9002EqualTo(BigDecimal value) {
            addCriterion("T0A9002 =", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002NotEqualTo(BigDecimal value) {
            addCriterion("T0A9002 <>", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002GreaterThan(BigDecimal value) {
            addCriterion("T0A9002 >", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("T0A9002 >=", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002LessThan(BigDecimal value) {
            addCriterion("T0A9002 <", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002LessThanOrEqualTo(BigDecimal value) {
            addCriterion("T0A9002 <=", value, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002In(List<BigDecimal> values) {
            addCriterion("T0A9002 in", values, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002NotIn(List<BigDecimal> values) {
            addCriterion("T0A9002 not in", values, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("T0A9002 between", value1, value2, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9002NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("T0A9002 not between", value1, value2, "t0a9002");
            return (Criteria) this;
        }

        public Criteria andT0a9101IsNull() {
            addCriterion("T0A9101 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9101IsNotNull() {
            addCriterion("T0A9101 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9101EqualTo(Short value) {
            addCriterion("T0A9101 =", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101NotEqualTo(Short value) {
            addCriterion("T0A9101 <>", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101GreaterThan(Short value) {
            addCriterion("T0A9101 >", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101GreaterThanOrEqualTo(Short value) {
            addCriterion("T0A9101 >=", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101LessThan(Short value) {
            addCriterion("T0A9101 <", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101LessThanOrEqualTo(Short value) {
            addCriterion("T0A9101 <=", value, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101In(List<Short> values) {
            addCriterion("T0A9101 in", values, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101NotIn(List<Short> values) {
            addCriterion("T0A9101 not in", values, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101Between(Short value1, Short value2) {
            addCriterion("T0A9101 between", value1, value2, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9101NotBetween(Short value1, Short value2) {
            addCriterion("T0A9101 not between", value1, value2, "t0a9101");
            return (Criteria) this;
        }

        public Criteria andT0a9102IsNull() {
            addCriterion("T0A9102 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9102IsNotNull() {
            addCriterion("T0A9102 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9102EqualTo(String value) {
            addCriterion("T0A9102 =", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102NotEqualTo(String value) {
            addCriterion("T0A9102 <>", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102GreaterThan(String value) {
            addCriterion("T0A9102 >", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102GreaterThanOrEqualTo(String value) {
            addCriterion("T0A9102 >=", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102LessThan(String value) {
            addCriterion("T0A9102 <", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102LessThanOrEqualTo(String value) {
            addCriterion("T0A9102 <=", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102Like(String value) {
            addCriterion("T0A9102 like", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102NotLike(String value) {
            addCriterion("T0A9102 not like", value, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102In(List<String> values) {
            addCriterion("T0A9102 in", values, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102NotIn(List<String> values) {
            addCriterion("T0A9102 not in", values, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102Between(String value1, String value2) {
            addCriterion("T0A9102 between", value1, value2, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9102NotBetween(String value1, String value2) {
            addCriterion("T0A9102 not between", value1, value2, "t0a9102");
            return (Criteria) this;
        }

        public Criteria andT0a9103IsNull() {
            addCriterion("T0A9103 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9103IsNotNull() {
            addCriterion("T0A9103 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9103EqualTo(String value) {
            addCriterion("T0A9103 =", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103NotEqualTo(String value) {
            addCriterion("T0A9103 <>", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103GreaterThan(String value) {
            addCriterion("T0A9103 >", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103GreaterThanOrEqualTo(String value) {
            addCriterion("T0A9103 >=", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103LessThan(String value) {
            addCriterion("T0A9103 <", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103LessThanOrEqualTo(String value) {
            addCriterion("T0A9103 <=", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103Like(String value) {
            addCriterion("T0A9103 like", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103NotLike(String value) {
            addCriterion("T0A9103 not like", value, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103In(List<String> values) {
            addCriterion("T0A9103 in", values, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103NotIn(List<String> values) {
            addCriterion("T0A9103 not in", values, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103Between(String value1, String value2) {
            addCriterion("T0A9103 between", value1, value2, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9103NotBetween(String value1, String value2) {
            addCriterion("T0A9103 not between", value1, value2, "t0a9103");
            return (Criteria) this;
        }

        public Criteria andT0a9201IsNull() {
            addCriterion("T0A9201 is null");
            return (Criteria) this;
        }

        public Criteria andT0a9201IsNotNull() {
            addCriterion("T0A9201 is not null");
            return (Criteria) this;
        }

        public Criteria andT0a9201EqualTo(String value) {
            addCriterion("T0A9201 =", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201NotEqualTo(String value) {
            addCriterion("T0A9201 <>", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201GreaterThan(String value) {
            addCriterion("T0A9201 >", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201GreaterThanOrEqualTo(String value) {
            addCriterion("T0A9201 >=", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201LessThan(String value) {
            addCriterion("T0A9201 <", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201LessThanOrEqualTo(String value) {
            addCriterion("T0A9201 <=", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201Like(String value) {
            addCriterion("T0A9201 like", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201NotLike(String value) {
            addCriterion("T0A9201 not like", value, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201In(List<String> values) {
            addCriterion("T0A9201 in", values, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201NotIn(List<String> values) {
            addCriterion("T0A9201 not in", values, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201Between(String value1, String value2) {
            addCriterion("T0A9201 between", value1, value2, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andT0a9201NotBetween(String value1, String value2) {
            addCriterion("T0A9201 not between", value1, value2, "t0a9201");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("UPDATE_APP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("UPDATE_APP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("UPDATE_APP =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("UPDATE_APP <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("UPDATE_APP >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("UPDATE_APP <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("UPDATE_APP like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("UPDATE_APP not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("UPDATE_APP in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("UPDATE_APP not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("UPDATE_APP between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("UPDATE_APP not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("VERSION_NO is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("VERSION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(BigDecimal value) {
            addCriterion("VERSION_NO >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(BigDecimal value) {
            addCriterion("VERSION_NO <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO not between", value1, value2, "versionNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T0A9
     *
     * @mbggenerated do_not_delete_during_merge Sat May 21 21:52:31 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T0A9
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}