package com.common.dao.model;

import java.math.BigDecimal;

public class Te17Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17001
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    private String te17001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17002
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    private String te17002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17003
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    private BigDecimal te17003;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17001
     *
     * @return the value of TE17.TE17001
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public String getTe17001() {
        return te17001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17001
     *
     * @param te17001 the value for TE17.TE17001
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public void setTe17001(String te17001) {
        this.te17001 = te17001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17002
     *
     * @return the value of TE17.TE17002
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public String getTe17002() {
        return te17002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17002
     *
     * @param te17002 the value for TE17.TE17002
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public void setTe17002(String te17002) {
        this.te17002 = te17002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17003
     *
     * @return the value of TE17.TE17003
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public BigDecimal getTe17003() {
        return te17003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17003
     *
     * @param te17003 the value for TE17.TE17003
     *
     * @mbggenerated Sun May 22 09:36:06 JST 2016
     */
    public void setTe17003(BigDecimal te17003) {
        this.te17003 = te17003;
    }
}