package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te72 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.TE72001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String te72001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.TE72101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Integer te72101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE72.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.TE72001
     *
     * @return the value of TE72.TE72001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getTe72001() {
        return te72001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.TE72001
     *
     * @param te72001 the value for TE72.TE72001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe72001(String te72001) {
        this.te72001 = te72001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.TE72101
     *
     * @return the value of TE72.TE72101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Integer getTe72101() {
        return te72101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.TE72101
     *
     * @param te72101 the value for TE72.TE72101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe72101(Integer te72101) {
        this.te72101 = te72101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.CREATOR
     *
     * @return the value of TE72.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.CREATOR
     *
     * @param creator the value for TE72.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.CREATE_TIMESTAMP
     *
     * @return the value of TE72.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE72.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.UPDATER
     *
     * @return the value of TE72.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.UPDATER
     *
     * @param updater the value for TE72.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.UPDATE_TIMESTAMP
     *
     * @return the value of TE72.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE72.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.UPDATE_APP
     *
     * @return the value of TE72.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.UPDATE_APP
     *
     * @param updateApp the value for TE72.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE72.VERSION_NO
     *
     * @return the value of TE72.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE72.VERSION_NO
     *
     * @param versionNo the value for TE72.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}