package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te73 extends Te73Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String te73101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73201
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String te73201;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73301
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String te73301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73401
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Short te73401;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73501
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private BigDecimal te73501;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73601
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private BigDecimal te73601;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73101
     *
     * @return the value of TE73.TE73101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getTe73101() {
        return te73101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73101
     *
     * @param te73101 the value for TE73.TE73101
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73101(String te73101) {
        this.te73101 = te73101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73201
     *
     * @return the value of TE73.TE73201
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getTe73201() {
        return te73201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73201
     *
     * @param te73201 the value for TE73.TE73201
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73201(String te73201) {
        this.te73201 = te73201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73301
     *
     * @return the value of TE73.TE73301
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getTe73301() {
        return te73301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73301
     *
     * @param te73301 the value for TE73.TE73301
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73301(String te73301) {
        this.te73301 = te73301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73401
     *
     * @return the value of TE73.TE73401
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Short getTe73401() {
        return te73401;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73401
     *
     * @param te73401 the value for TE73.TE73401
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73401(Short te73401) {
        this.te73401 = te73401;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73501
     *
     * @return the value of TE73.TE73501
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public BigDecimal getTe73501() {
        return te73501;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73501
     *
     * @param te73501 the value for TE73.TE73501
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73501(BigDecimal te73501) {
        this.te73501 = te73501;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73601
     *
     * @return the value of TE73.TE73601
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public BigDecimal getTe73601() {
        return te73601;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73601
     *
     * @param te73601 the value for TE73.TE73601
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe73601(BigDecimal te73601) {
        this.te73601 = te73601;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.CREATOR
     *
     * @return the value of TE73.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.CREATOR
     *
     * @param creator the value for TE73.CREATOR
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.CREATE_TIMESTAMP
     *
     * @return the value of TE73.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE73.CREATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.UPDATER
     *
     * @return the value of TE73.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.UPDATER
     *
     * @param updater the value for TE73.UPDATER
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.UPDATE_TIMESTAMP
     *
     * @return the value of TE73.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE73.UPDATE_TIMESTAMP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.UPDATE_APP
     *
     * @return the value of TE73.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.UPDATE_APP
     *
     * @param updateApp the value for TE73.UPDATE_APP
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.VERSION_NO
     *
     * @return the value of TE73.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.VERSION_NO
     *
     * @param versionNo the value for TE73.VERSION_NO
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}