package com.common.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Te79Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Te79Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTe79001IsNull() {
            addCriterion("TE79001 is null");
            return (Criteria) this;
        }

        public Criteria andTe79001IsNotNull() {
            addCriterion("TE79001 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79001EqualTo(String value) {
            addCriterion("TE79001 =", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001NotEqualTo(String value) {
            addCriterion("TE79001 <>", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001GreaterThan(String value) {
            addCriterion("TE79001 >", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001GreaterThanOrEqualTo(String value) {
            addCriterion("TE79001 >=", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001LessThan(String value) {
            addCriterion("TE79001 <", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001LessThanOrEqualTo(String value) {
            addCriterion("TE79001 <=", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001Like(String value) {
            addCriterion("TE79001 like", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001NotLike(String value) {
            addCriterion("TE79001 not like", value, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001In(List<String> values) {
            addCriterion("TE79001 in", values, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001NotIn(List<String> values) {
            addCriterion("TE79001 not in", values, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001Between(String value1, String value2) {
            addCriterion("TE79001 between", value1, value2, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79001NotBetween(String value1, String value2) {
            addCriterion("TE79001 not between", value1, value2, "te79001");
            return (Criteria) this;
        }

        public Criteria andTe79002IsNull() {
            addCriterion("TE79002 is null");
            return (Criteria) this;
        }

        public Criteria andTe79002IsNotNull() {
            addCriterion("TE79002 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79002EqualTo(BigDecimal value) {
            addCriterion("TE79002 =", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002NotEqualTo(BigDecimal value) {
            addCriterion("TE79002 <>", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002GreaterThan(BigDecimal value) {
            addCriterion("TE79002 >", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TE79002 >=", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002LessThan(BigDecimal value) {
            addCriterion("TE79002 <", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002LessThanOrEqualTo(BigDecimal value) {
            addCriterion("TE79002 <=", value, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002In(List<BigDecimal> values) {
            addCriterion("TE79002 in", values, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002NotIn(List<BigDecimal> values) {
            addCriterion("TE79002 not in", values, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE79002 between", value1, value2, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79002NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE79002 not between", value1, value2, "te79002");
            return (Criteria) this;
        }

        public Criteria andTe79003IsNull() {
            addCriterion("TE79003 is null");
            return (Criteria) this;
        }

        public Criteria andTe79003IsNotNull() {
            addCriterion("TE79003 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79003EqualTo(Short value) {
            addCriterion("TE79003 =", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003NotEqualTo(Short value) {
            addCriterion("TE79003 <>", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003GreaterThan(Short value) {
            addCriterion("TE79003 >", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79003 >=", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003LessThan(Short value) {
            addCriterion("TE79003 <", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003LessThanOrEqualTo(Short value) {
            addCriterion("TE79003 <=", value, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003In(List<Short> values) {
            addCriterion("TE79003 in", values, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003NotIn(List<Short> values) {
            addCriterion("TE79003 not in", values, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003Between(Short value1, Short value2) {
            addCriterion("TE79003 between", value1, value2, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79003NotBetween(Short value1, Short value2) {
            addCriterion("TE79003 not between", value1, value2, "te79003");
            return (Criteria) this;
        }

        public Criteria andTe79101IsNull() {
            addCriterion("TE79101 is null");
            return (Criteria) this;
        }

        public Criteria andTe79101IsNotNull() {
            addCriterion("TE79101 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79101EqualTo(Date value) {
            addCriterion("TE79101 =", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101NotEqualTo(Date value) {
            addCriterion("TE79101 <>", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101GreaterThan(Date value) {
            addCriterion("TE79101 >", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101GreaterThanOrEqualTo(Date value) {
            addCriterion("TE79101 >=", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101LessThan(Date value) {
            addCriterion("TE79101 <", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101LessThanOrEqualTo(Date value) {
            addCriterion("TE79101 <=", value, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101In(List<Date> values) {
            addCriterion("TE79101 in", values, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101NotIn(List<Date> values) {
            addCriterion("TE79101 not in", values, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101Between(Date value1, Date value2) {
            addCriterion("TE79101 between", value1, value2, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79101NotBetween(Date value1, Date value2) {
            addCriterion("TE79101 not between", value1, value2, "te79101");
            return (Criteria) this;
        }

        public Criteria andTe79102IsNull() {
            addCriterion("TE79102 is null");
            return (Criteria) this;
        }

        public Criteria andTe79102IsNotNull() {
            addCriterion("TE79102 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79102EqualTo(Short value) {
            addCriterion("TE79102 =", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102NotEqualTo(Short value) {
            addCriterion("TE79102 <>", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102GreaterThan(Short value) {
            addCriterion("TE79102 >", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79102 >=", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102LessThan(Short value) {
            addCriterion("TE79102 <", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102LessThanOrEqualTo(Short value) {
            addCriterion("TE79102 <=", value, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102In(List<Short> values) {
            addCriterion("TE79102 in", values, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102NotIn(List<Short> values) {
            addCriterion("TE79102 not in", values, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102Between(Short value1, Short value2) {
            addCriterion("TE79102 between", value1, value2, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79102NotBetween(Short value1, Short value2) {
            addCriterion("TE79102 not between", value1, value2, "te79102");
            return (Criteria) this;
        }

        public Criteria andTe79103IsNull() {
            addCriterion("TE79103 is null");
            return (Criteria) this;
        }

        public Criteria andTe79103IsNotNull() {
            addCriterion("TE79103 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79103EqualTo(String value) {
            addCriterion("TE79103 =", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103NotEqualTo(String value) {
            addCriterion("TE79103 <>", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103GreaterThan(String value) {
            addCriterion("TE79103 >", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103GreaterThanOrEqualTo(String value) {
            addCriterion("TE79103 >=", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103LessThan(String value) {
            addCriterion("TE79103 <", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103LessThanOrEqualTo(String value) {
            addCriterion("TE79103 <=", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103Like(String value) {
            addCriterion("TE79103 like", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103NotLike(String value) {
            addCriterion("TE79103 not like", value, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103In(List<String> values) {
            addCriterion("TE79103 in", values, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103NotIn(List<String> values) {
            addCriterion("TE79103 not in", values, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103Between(String value1, String value2) {
            addCriterion("TE79103 between", value1, value2, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79103NotBetween(String value1, String value2) {
            addCriterion("TE79103 not between", value1, value2, "te79103");
            return (Criteria) this;
        }

        public Criteria andTe79104IsNull() {
            addCriterion("TE79104 is null");
            return (Criteria) this;
        }

        public Criteria andTe79104IsNotNull() {
            addCriterion("TE79104 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79104EqualTo(String value) {
            addCriterion("TE79104 =", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104NotEqualTo(String value) {
            addCriterion("TE79104 <>", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104GreaterThan(String value) {
            addCriterion("TE79104 >", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104GreaterThanOrEqualTo(String value) {
            addCriterion("TE79104 >=", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104LessThan(String value) {
            addCriterion("TE79104 <", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104LessThanOrEqualTo(String value) {
            addCriterion("TE79104 <=", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104Like(String value) {
            addCriterion("TE79104 like", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104NotLike(String value) {
            addCriterion("TE79104 not like", value, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104In(List<String> values) {
            addCriterion("TE79104 in", values, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104NotIn(List<String> values) {
            addCriterion("TE79104 not in", values, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104Between(String value1, String value2) {
            addCriterion("TE79104 between", value1, value2, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79104NotBetween(String value1, String value2) {
            addCriterion("TE79104 not between", value1, value2, "te79104");
            return (Criteria) this;
        }

        public Criteria andTe79105IsNull() {
            addCriterion("TE79105 is null");
            return (Criteria) this;
        }

        public Criteria andTe79105IsNotNull() {
            addCriterion("TE79105 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79105EqualTo(BigDecimal value) {
            addCriterion("TE79105 =", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105NotEqualTo(BigDecimal value) {
            addCriterion("TE79105 <>", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105GreaterThan(BigDecimal value) {
            addCriterion("TE79105 >", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TE79105 >=", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105LessThan(BigDecimal value) {
            addCriterion("TE79105 <", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105LessThanOrEqualTo(BigDecimal value) {
            addCriterion("TE79105 <=", value, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105In(List<BigDecimal> values) {
            addCriterion("TE79105 in", values, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105NotIn(List<BigDecimal> values) {
            addCriterion("TE79105 not in", values, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE79105 between", value1, value2, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79105NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE79105 not between", value1, value2, "te79105");
            return (Criteria) this;
        }

        public Criteria andTe79106IsNull() {
            addCriterion("TE79106 is null");
            return (Criteria) this;
        }

        public Criteria andTe79106IsNotNull() {
            addCriterion("TE79106 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79106EqualTo(Short value) {
            addCriterion("TE79106 =", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106NotEqualTo(Short value) {
            addCriterion("TE79106 <>", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106GreaterThan(Short value) {
            addCriterion("TE79106 >", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79106 >=", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106LessThan(Short value) {
            addCriterion("TE79106 <", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106LessThanOrEqualTo(Short value) {
            addCriterion("TE79106 <=", value, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106In(List<Short> values) {
            addCriterion("TE79106 in", values, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106NotIn(List<Short> values) {
            addCriterion("TE79106 not in", values, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106Between(Short value1, Short value2) {
            addCriterion("TE79106 between", value1, value2, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79106NotBetween(Short value1, Short value2) {
            addCriterion("TE79106 not between", value1, value2, "te79106");
            return (Criteria) this;
        }

        public Criteria andTe79107IsNull() {
            addCriterion("TE79107 is null");
            return (Criteria) this;
        }

        public Criteria andTe79107IsNotNull() {
            addCriterion("TE79107 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79107EqualTo(String value) {
            addCriterion("TE79107 =", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107NotEqualTo(String value) {
            addCriterion("TE79107 <>", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107GreaterThan(String value) {
            addCriterion("TE79107 >", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107GreaterThanOrEqualTo(String value) {
            addCriterion("TE79107 >=", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107LessThan(String value) {
            addCriterion("TE79107 <", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107LessThanOrEqualTo(String value) {
            addCriterion("TE79107 <=", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107Like(String value) {
            addCriterion("TE79107 like", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107NotLike(String value) {
            addCriterion("TE79107 not like", value, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107In(List<String> values) {
            addCriterion("TE79107 in", values, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107NotIn(List<String> values) {
            addCriterion("TE79107 not in", values, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107Between(String value1, String value2) {
            addCriterion("TE79107 between", value1, value2, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79107NotBetween(String value1, String value2) {
            addCriterion("TE79107 not between", value1, value2, "te79107");
            return (Criteria) this;
        }

        public Criteria andTe79201IsNull() {
            addCriterion("TE79201 is null");
            return (Criteria) this;
        }

        public Criteria andTe79201IsNotNull() {
            addCriterion("TE79201 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79201EqualTo(Date value) {
            addCriterion("TE79201 =", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201NotEqualTo(Date value) {
            addCriterion("TE79201 <>", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201GreaterThan(Date value) {
            addCriterion("TE79201 >", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201GreaterThanOrEqualTo(Date value) {
            addCriterion("TE79201 >=", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201LessThan(Date value) {
            addCriterion("TE79201 <", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201LessThanOrEqualTo(Date value) {
            addCriterion("TE79201 <=", value, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201In(List<Date> values) {
            addCriterion("TE79201 in", values, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201NotIn(List<Date> values) {
            addCriterion("TE79201 not in", values, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201Between(Date value1, Date value2) {
            addCriterion("TE79201 between", value1, value2, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79201NotBetween(Date value1, Date value2) {
            addCriterion("TE79201 not between", value1, value2, "te79201");
            return (Criteria) this;
        }

        public Criteria andTe79202IsNull() {
            addCriterion("TE79202 is null");
            return (Criteria) this;
        }

        public Criteria andTe79202IsNotNull() {
            addCriterion("TE79202 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79202EqualTo(Short value) {
            addCriterion("TE79202 =", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202NotEqualTo(Short value) {
            addCriterion("TE79202 <>", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202GreaterThan(Short value) {
            addCriterion("TE79202 >", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79202 >=", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202LessThan(Short value) {
            addCriterion("TE79202 <", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202LessThanOrEqualTo(Short value) {
            addCriterion("TE79202 <=", value, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202In(List<Short> values) {
            addCriterion("TE79202 in", values, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202NotIn(List<Short> values) {
            addCriterion("TE79202 not in", values, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202Between(Short value1, Short value2) {
            addCriterion("TE79202 between", value1, value2, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79202NotBetween(Short value1, Short value2) {
            addCriterion("TE79202 not between", value1, value2, "te79202");
            return (Criteria) this;
        }

        public Criteria andTe79203IsNull() {
            addCriterion("TE79203 is null");
            return (Criteria) this;
        }

        public Criteria andTe79203IsNotNull() {
            addCriterion("TE79203 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79203EqualTo(String value) {
            addCriterion("TE79203 =", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203NotEqualTo(String value) {
            addCriterion("TE79203 <>", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203GreaterThan(String value) {
            addCriterion("TE79203 >", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203GreaterThanOrEqualTo(String value) {
            addCriterion("TE79203 >=", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203LessThan(String value) {
            addCriterion("TE79203 <", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203LessThanOrEqualTo(String value) {
            addCriterion("TE79203 <=", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203Like(String value) {
            addCriterion("TE79203 like", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203NotLike(String value) {
            addCriterion("TE79203 not like", value, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203In(List<String> values) {
            addCriterion("TE79203 in", values, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203NotIn(List<String> values) {
            addCriterion("TE79203 not in", values, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203Between(String value1, String value2) {
            addCriterion("TE79203 between", value1, value2, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79203NotBetween(String value1, String value2) {
            addCriterion("TE79203 not between", value1, value2, "te79203");
            return (Criteria) this;
        }

        public Criteria andTe79301IsNull() {
            addCriterion("TE79301 is null");
            return (Criteria) this;
        }

        public Criteria andTe79301IsNotNull() {
            addCriterion("TE79301 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79301EqualTo(Short value) {
            addCriterion("TE79301 =", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301NotEqualTo(Short value) {
            addCriterion("TE79301 <>", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301GreaterThan(Short value) {
            addCriterion("TE79301 >", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79301 >=", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301LessThan(Short value) {
            addCriterion("TE79301 <", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301LessThanOrEqualTo(Short value) {
            addCriterion("TE79301 <=", value, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301In(List<Short> values) {
            addCriterion("TE79301 in", values, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301NotIn(List<Short> values) {
            addCriterion("TE79301 not in", values, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301Between(Short value1, Short value2) {
            addCriterion("TE79301 between", value1, value2, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79301NotBetween(Short value1, Short value2) {
            addCriterion("TE79301 not between", value1, value2, "te79301");
            return (Criteria) this;
        }

        public Criteria andTe79302IsNull() {
            addCriterion("TE79302 is null");
            return (Criteria) this;
        }

        public Criteria andTe79302IsNotNull() {
            addCriterion("TE79302 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79302EqualTo(String value) {
            addCriterion("TE79302 =", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302NotEqualTo(String value) {
            addCriterion("TE79302 <>", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302GreaterThan(String value) {
            addCriterion("TE79302 >", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302GreaterThanOrEqualTo(String value) {
            addCriterion("TE79302 >=", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302LessThan(String value) {
            addCriterion("TE79302 <", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302LessThanOrEqualTo(String value) {
            addCriterion("TE79302 <=", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302Like(String value) {
            addCriterion("TE79302 like", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302NotLike(String value) {
            addCriterion("TE79302 not like", value, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302In(List<String> values) {
            addCriterion("TE79302 in", values, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302NotIn(List<String> values) {
            addCriterion("TE79302 not in", values, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302Between(String value1, String value2) {
            addCriterion("TE79302 between", value1, value2, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79302NotBetween(String value1, String value2) {
            addCriterion("TE79302 not between", value1, value2, "te79302");
            return (Criteria) this;
        }

        public Criteria andTe79401IsNull() {
            addCriterion("TE79401 is null");
            return (Criteria) this;
        }

        public Criteria andTe79401IsNotNull() {
            addCriterion("TE79401 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79401EqualTo(String value) {
            addCriterion("TE79401 =", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401NotEqualTo(String value) {
            addCriterion("TE79401 <>", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401GreaterThan(String value) {
            addCriterion("TE79401 >", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401GreaterThanOrEqualTo(String value) {
            addCriterion("TE79401 >=", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401LessThan(String value) {
            addCriterion("TE79401 <", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401LessThanOrEqualTo(String value) {
            addCriterion("TE79401 <=", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401Like(String value) {
            addCriterion("TE79401 like", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401NotLike(String value) {
            addCriterion("TE79401 not like", value, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401In(List<String> values) {
            addCriterion("TE79401 in", values, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401NotIn(List<String> values) {
            addCriterion("TE79401 not in", values, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401Between(String value1, String value2) {
            addCriterion("TE79401 between", value1, value2, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79401NotBetween(String value1, String value2) {
            addCriterion("TE79401 not between", value1, value2, "te79401");
            return (Criteria) this;
        }

        public Criteria andTe79402IsNull() {
            addCriterion("TE79402 is null");
            return (Criteria) this;
        }

        public Criteria andTe79402IsNotNull() {
            addCriterion("TE79402 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79402EqualTo(String value) {
            addCriterion("TE79402 =", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402NotEqualTo(String value) {
            addCriterion("TE79402 <>", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402GreaterThan(String value) {
            addCriterion("TE79402 >", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402GreaterThanOrEqualTo(String value) {
            addCriterion("TE79402 >=", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402LessThan(String value) {
            addCriterion("TE79402 <", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402LessThanOrEqualTo(String value) {
            addCriterion("TE79402 <=", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402Like(String value) {
            addCriterion("TE79402 like", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402NotLike(String value) {
            addCriterion("TE79402 not like", value, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402In(List<String> values) {
            addCriterion("TE79402 in", values, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402NotIn(List<String> values) {
            addCriterion("TE79402 not in", values, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402Between(String value1, String value2) {
            addCriterion("TE79402 between", value1, value2, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79402NotBetween(String value1, String value2) {
            addCriterion("TE79402 not between", value1, value2, "te79402");
            return (Criteria) this;
        }

        public Criteria andTe79501IsNull() {
            addCriterion("TE79501 is null");
            return (Criteria) this;
        }

        public Criteria andTe79501IsNotNull() {
            addCriterion("TE79501 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79501EqualTo(String value) {
            addCriterion("TE79501 =", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501NotEqualTo(String value) {
            addCriterion("TE79501 <>", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501GreaterThan(String value) {
            addCriterion("TE79501 >", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501GreaterThanOrEqualTo(String value) {
            addCriterion("TE79501 >=", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501LessThan(String value) {
            addCriterion("TE79501 <", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501LessThanOrEqualTo(String value) {
            addCriterion("TE79501 <=", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501Like(String value) {
            addCriterion("TE79501 like", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501NotLike(String value) {
            addCriterion("TE79501 not like", value, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501In(List<String> values) {
            addCriterion("TE79501 in", values, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501NotIn(List<String> values) {
            addCriterion("TE79501 not in", values, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501Between(String value1, String value2) {
            addCriterion("TE79501 between", value1, value2, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79501NotBetween(String value1, String value2) {
            addCriterion("TE79501 not between", value1, value2, "te79501");
            return (Criteria) this;
        }

        public Criteria andTe79601IsNull() {
            addCriterion("TE79601 is null");
            return (Criteria) this;
        }

        public Criteria andTe79601IsNotNull() {
            addCriterion("TE79601 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79601EqualTo(String value) {
            addCriterion("TE79601 =", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601NotEqualTo(String value) {
            addCriterion("TE79601 <>", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601GreaterThan(String value) {
            addCriterion("TE79601 >", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601GreaterThanOrEqualTo(String value) {
            addCriterion("TE79601 >=", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601LessThan(String value) {
            addCriterion("TE79601 <", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601LessThanOrEqualTo(String value) {
            addCriterion("TE79601 <=", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601Like(String value) {
            addCriterion("TE79601 like", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601NotLike(String value) {
            addCriterion("TE79601 not like", value, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601In(List<String> values) {
            addCriterion("TE79601 in", values, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601NotIn(List<String> values) {
            addCriterion("TE79601 not in", values, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601Between(String value1, String value2) {
            addCriterion("TE79601 between", value1, value2, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79601NotBetween(String value1, String value2) {
            addCriterion("TE79601 not between", value1, value2, "te79601");
            return (Criteria) this;
        }

        public Criteria andTe79701IsNull() {
            addCriterion("TE79701 is null");
            return (Criteria) this;
        }

        public Criteria andTe79701IsNotNull() {
            addCriterion("TE79701 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79701EqualTo(String value) {
            addCriterion("TE79701 =", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701NotEqualTo(String value) {
            addCriterion("TE79701 <>", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701GreaterThan(String value) {
            addCriterion("TE79701 >", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701GreaterThanOrEqualTo(String value) {
            addCriterion("TE79701 >=", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701LessThan(String value) {
            addCriterion("TE79701 <", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701LessThanOrEqualTo(String value) {
            addCriterion("TE79701 <=", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701Like(String value) {
            addCriterion("TE79701 like", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701NotLike(String value) {
            addCriterion("TE79701 not like", value, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701In(List<String> values) {
            addCriterion("TE79701 in", values, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701NotIn(List<String> values) {
            addCriterion("TE79701 not in", values, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701Between(String value1, String value2) {
            addCriterion("TE79701 between", value1, value2, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79701NotBetween(String value1, String value2) {
            addCriterion("TE79701 not between", value1, value2, "te79701");
            return (Criteria) this;
        }

        public Criteria andTe79801IsNull() {
            addCriterion("TE79801 is null");
            return (Criteria) this;
        }

        public Criteria andTe79801IsNotNull() {
            addCriterion("TE79801 is not null");
            return (Criteria) this;
        }

        public Criteria andTe79801EqualTo(Short value) {
            addCriterion("TE79801 =", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801NotEqualTo(Short value) {
            addCriterion("TE79801 <>", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801GreaterThan(Short value) {
            addCriterion("TE79801 >", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801GreaterThanOrEqualTo(Short value) {
            addCriterion("TE79801 >=", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801LessThan(Short value) {
            addCriterion("TE79801 <", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801LessThanOrEqualTo(Short value) {
            addCriterion("TE79801 <=", value, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801In(List<Short> values) {
            addCriterion("TE79801 in", values, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801NotIn(List<Short> values) {
            addCriterion("TE79801 not in", values, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801Between(Short value1, Short value2) {
            addCriterion("TE79801 between", value1, value2, "te79801");
            return (Criteria) this;
        }

        public Criteria andTe79801NotBetween(Short value1, Short value2) {
            addCriterion("TE79801 not between", value1, value2, "te79801");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("UPDATE_APP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("UPDATE_APP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("UPDATE_APP =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("UPDATE_APP <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("UPDATE_APP >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("UPDATE_APP <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("UPDATE_APP like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("UPDATE_APP not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("UPDATE_APP in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("UPDATE_APP not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("UPDATE_APP between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("UPDATE_APP not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("VERSION_NO is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("VERSION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(BigDecimal value) {
            addCriterion("VERSION_NO >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(BigDecimal value) {
            addCriterion("VERSION_NO <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO not between", value1, value2, "versionNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE79
     *
     * @mbggenerated do_not_delete_during_merge Sat May 21 21:52:31 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE79
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}