package com.common.dao.model;

import java.math.BigDecimal;

public class Te7aKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A001
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    private String te7a001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A002
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    private BigDecimal te7a002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A003
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    private Short te7a003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A004
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    private Short te7a004;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A005
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    private String te7a005;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A001
     *
     * @return the value of TE7A.TE7A001
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public String getTe7a001() {
        return te7a001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A001
     *
     * @param te7a001 the value for TE7A.TE7A001
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public void setTe7a001(String te7a001) {
        this.te7a001 = te7a001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A002
     *
     * @return the value of TE7A.TE7A002
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public BigDecimal getTe7a002() {
        return te7a002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A002
     *
     * @param te7a002 the value for TE7A.TE7A002
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public void setTe7a002(BigDecimal te7a002) {
        this.te7a002 = te7a002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A003
     *
     * @return the value of TE7A.TE7A003
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public Short getTe7a003() {
        return te7a003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A003
     *
     * @param te7a003 the value for TE7A.TE7A003
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public void setTe7a003(Short te7a003) {
        this.te7a003 = te7a003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A004
     *
     * @return the value of TE7A.TE7A004
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public Short getTe7a004() {
        return te7a004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A004
     *
     * @param te7a004 the value for TE7A.TE7A004
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public void setTe7a004(Short te7a004) {
        this.te7a004 = te7a004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A005
     *
     * @return the value of TE7A.TE7A005
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public String getTe7a005() {
        return te7a005;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A005
     *
     * @param te7a005 the value for TE7A.TE7A005
     *
     * @mbggenerated Sun May 22 01:02:46 JST 2016
     */
    public void setTe7a005(String te7a005) {
        this.te7a005 = te7a005;
    }
}