package com.common.dao.model;

public class T105Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T105.T105001
     *
     * @mbggenerated
     */
    private String t105001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T105.T105002
     *
     * @mbggenerated
     */
    private String t105002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T105.T105003
     *
     * @mbggenerated
     */
    private Short t105003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T105.T105004
     *
     * @mbggenerated
     */
    private Short t105004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T105.T105001
     *
     * @return the value of T105.T105001
     *
     * @mbggenerated
     */
    public String getT105001() {
        return t105001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T105.T105001
     *
     * @param t105001 the value for T105.T105001
     *
     * @mbggenerated
     */
    public void setT105001(String t105001) {
        this.t105001 = t105001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T105.T105002
     *
     * @return the value of T105.T105002
     *
     * @mbggenerated
     */
    public String getT105002() {
        return t105002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T105.T105002
     *
     * @param t105002 the value for T105.T105002
     *
     * @mbggenerated
     */
    public void setT105002(String t105002) {
        this.t105002 = t105002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T105.T105003
     *
     * @return the value of T105.T105003
     *
     * @mbggenerated
     */
    public Short getT105003() {
        return t105003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T105.T105003
     *
     * @param t105003 the value for T105.T105003
     *
     * @mbggenerated
     */
    public void setT105003(Short t105003) {
        this.t105003 = t105003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T105.T105004
     *
     * @return the value of T105.T105004
     *
     * @mbggenerated
     */
    public Short getT105004() {
        return t105004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T105.T105004
     *
     * @param t105004 the value for T105.T105004
     *
     * @mbggenerated
     */
    public void setT105004(Short t105004) {
        this.t105004 = t105004;
    }
}