package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te17 extends Te17Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17101
     *
     * @mbggenerated
     */
    private String te17101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17201
     *
     * @mbggenerated
     */
    private Short te17201;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17202
     *
     * @mbggenerated
     */
    private Short te17202;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17203
     *
     * @mbggenerated
     */
    private Short te17203;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17204
     *
     * @mbggenerated
     */
    private Short te17204;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17205
     *
     * @mbggenerated
     */
    private Short te17205;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17206
     *
     * @mbggenerated
     */
    private Short te17206;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17207
     *
     * @mbggenerated
     */
    private Short te17207;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17208
     *
     * @mbggenerated
     */
    private Short te17208;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17209
     *
     * @mbggenerated
     */
    private Short te17209;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17210
     *
     * @mbggenerated
     */
    private Short te17210;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17211
     *
     * @mbggenerated
     */
    private Short te17211;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17212
     *
     * @mbggenerated
     */
    private Short te17212;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17213
     *
     * @mbggenerated
     */
    private Short te17213;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17214
     *
     * @mbggenerated
     */
    private Short te17214;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17215
     *
     * @mbggenerated
     */
    private Short te17215;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17216
     *
     * @mbggenerated
     */
    private Short te17216;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17217
     *
     * @mbggenerated
     */
    private Short te17217;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17218
     *
     * @mbggenerated
     */
    private Short te17218;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17219
     *
     * @mbggenerated
     */
    private Short te17219;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17220
     *
     * @mbggenerated
     */
    private Short te17220;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17221
     *
     * @mbggenerated
     */
    private Short te17221;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17222
     *
     * @mbggenerated
     */
    private Short te17222;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17223
     *
     * @mbggenerated
     */
    private Short te17223;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17224
     *
     * @mbggenerated
     */
    private Short te17224;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17225
     *
     * @mbggenerated
     */
    private Short te17225;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17226
     *
     * @mbggenerated
     */
    private Short te17226;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17227
     *
     * @mbggenerated
     */
    private Short te17227;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17228
     *
     * @mbggenerated
     */
    private Short te17228;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17229
     *
     * @mbggenerated
     */
    private Short te17229;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17230
     *
     * @mbggenerated
     */
    private Short te17230;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17301
     *
     * @mbggenerated
     */
    private String te17301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17302
     *
     * @mbggenerated
     */
    private String te17302;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17303
     *
     * @mbggenerated
     */
    private String te17303;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17304
     *
     * @mbggenerated
     */
    private String te17304;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17305
     *
     * @mbggenerated
     */
    private String te17305;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.TE17306
     *
     * @mbggenerated
     */
    private String te17306;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.UPDATER
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.UPDATE_APP
     *
     * @mbggenerated
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE17.VERSION_NO
     *
     * @mbggenerated
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17101
     *
     * @return the value of TE17.TE17101
     *
     * @mbggenerated
     */
    public String getTe17101() {
        return te17101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17101
     *
     * @param te17101 the value for TE17.TE17101
     *
     * @mbggenerated
     */
    public void setTe17101(String te17101) {
        this.te17101 = te17101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17201
     *
     * @return the value of TE17.TE17201
     *
     * @mbggenerated
     */
    public Short getTe17201() {
        return te17201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17201
     *
     * @param te17201 the value for TE17.TE17201
     *
     * @mbggenerated
     */
    public void setTe17201(Short te17201) {
        this.te17201 = te17201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17202
     *
     * @return the value of TE17.TE17202
     *
     * @mbggenerated
     */
    public Short getTe17202() {
        return te17202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17202
     *
     * @param te17202 the value for TE17.TE17202
     *
     * @mbggenerated
     */
    public void setTe17202(Short te17202) {
        this.te17202 = te17202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17203
     *
     * @return the value of TE17.TE17203
     *
     * @mbggenerated
     */
    public Short getTe17203() {
        return te17203;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17203
     *
     * @param te17203 the value for TE17.TE17203
     *
     * @mbggenerated
     */
    public void setTe17203(Short te17203) {
        this.te17203 = te17203;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17204
     *
     * @return the value of TE17.TE17204
     *
     * @mbggenerated
     */
    public Short getTe17204() {
        return te17204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17204
     *
     * @param te17204 the value for TE17.TE17204
     *
     * @mbggenerated
     */
    public void setTe17204(Short te17204) {
        this.te17204 = te17204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17205
     *
     * @return the value of TE17.TE17205
     *
     * @mbggenerated
     */
    public Short getTe17205() {
        return te17205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17205
     *
     * @param te17205 the value for TE17.TE17205
     *
     * @mbggenerated
     */
    public void setTe17205(Short te17205) {
        this.te17205 = te17205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17206
     *
     * @return the value of TE17.TE17206
     *
     * @mbggenerated
     */
    public Short getTe17206() {
        return te17206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17206
     *
     * @param te17206 the value for TE17.TE17206
     *
     * @mbggenerated
     */
    public void setTe17206(Short te17206) {
        this.te17206 = te17206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17207
     *
     * @return the value of TE17.TE17207
     *
     * @mbggenerated
     */
    public Short getTe17207() {
        return te17207;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17207
     *
     * @param te17207 the value for TE17.TE17207
     *
     * @mbggenerated
     */
    public void setTe17207(Short te17207) {
        this.te17207 = te17207;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17208
     *
     * @return the value of TE17.TE17208
     *
     * @mbggenerated
     */
    public Short getTe17208() {
        return te17208;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17208
     *
     * @param te17208 the value for TE17.TE17208
     *
     * @mbggenerated
     */
    public void setTe17208(Short te17208) {
        this.te17208 = te17208;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17209
     *
     * @return the value of TE17.TE17209
     *
     * @mbggenerated
     */
    public Short getTe17209() {
        return te17209;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17209
     *
     * @param te17209 the value for TE17.TE17209
     *
     * @mbggenerated
     */
    public void setTe17209(Short te17209) {
        this.te17209 = te17209;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17210
     *
     * @return the value of TE17.TE17210
     *
     * @mbggenerated
     */
    public Short getTe17210() {
        return te17210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17210
     *
     * @param te17210 the value for TE17.TE17210
     *
     * @mbggenerated
     */
    public void setTe17210(Short te17210) {
        this.te17210 = te17210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17211
     *
     * @return the value of TE17.TE17211
     *
     * @mbggenerated
     */
    public Short getTe17211() {
        return te17211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17211
     *
     * @param te17211 the value for TE17.TE17211
     *
     * @mbggenerated
     */
    public void setTe17211(Short te17211) {
        this.te17211 = te17211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17212
     *
     * @return the value of TE17.TE17212
     *
     * @mbggenerated
     */
    public Short getTe17212() {
        return te17212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17212
     *
     * @param te17212 the value for TE17.TE17212
     *
     * @mbggenerated
     */
    public void setTe17212(Short te17212) {
        this.te17212 = te17212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17213
     *
     * @return the value of TE17.TE17213
     *
     * @mbggenerated
     */
    public Short getTe17213() {
        return te17213;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17213
     *
     * @param te17213 the value for TE17.TE17213
     *
     * @mbggenerated
     */
    public void setTe17213(Short te17213) {
        this.te17213 = te17213;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17214
     *
     * @return the value of TE17.TE17214
     *
     * @mbggenerated
     */
    public Short getTe17214() {
        return te17214;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17214
     *
     * @param te17214 the value for TE17.TE17214
     *
     * @mbggenerated
     */
    public void setTe17214(Short te17214) {
        this.te17214 = te17214;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17215
     *
     * @return the value of TE17.TE17215
     *
     * @mbggenerated
     */
    public Short getTe17215() {
        return te17215;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17215
     *
     * @param te17215 the value for TE17.TE17215
     *
     * @mbggenerated
     */
    public void setTe17215(Short te17215) {
        this.te17215 = te17215;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17216
     *
     * @return the value of TE17.TE17216
     *
     * @mbggenerated
     */
    public Short getTe17216() {
        return te17216;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17216
     *
     * @param te17216 the value for TE17.TE17216
     *
     * @mbggenerated
     */
    public void setTe17216(Short te17216) {
        this.te17216 = te17216;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17217
     *
     * @return the value of TE17.TE17217
     *
     * @mbggenerated
     */
    public Short getTe17217() {
        return te17217;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17217
     *
     * @param te17217 the value for TE17.TE17217
     *
     * @mbggenerated
     */
    public void setTe17217(Short te17217) {
        this.te17217 = te17217;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17218
     *
     * @return the value of TE17.TE17218
     *
     * @mbggenerated
     */
    public Short getTe17218() {
        return te17218;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17218
     *
     * @param te17218 the value for TE17.TE17218
     *
     * @mbggenerated
     */
    public void setTe17218(Short te17218) {
        this.te17218 = te17218;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17219
     *
     * @return the value of TE17.TE17219
     *
     * @mbggenerated
     */
    public Short getTe17219() {
        return te17219;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17219
     *
     * @param te17219 the value for TE17.TE17219
     *
     * @mbggenerated
     */
    public void setTe17219(Short te17219) {
        this.te17219 = te17219;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17220
     *
     * @return the value of TE17.TE17220
     *
     * @mbggenerated
     */
    public Short getTe17220() {
        return te17220;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17220
     *
     * @param te17220 the value for TE17.TE17220
     *
     * @mbggenerated
     */
    public void setTe17220(Short te17220) {
        this.te17220 = te17220;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17221
     *
     * @return the value of TE17.TE17221
     *
     * @mbggenerated
     */
    public Short getTe17221() {
        return te17221;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17221
     *
     * @param te17221 the value for TE17.TE17221
     *
     * @mbggenerated
     */
    public void setTe17221(Short te17221) {
        this.te17221 = te17221;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17222
     *
     * @return the value of TE17.TE17222
     *
     * @mbggenerated
     */
    public Short getTe17222() {
        return te17222;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17222
     *
     * @param te17222 the value for TE17.TE17222
     *
     * @mbggenerated
     */
    public void setTe17222(Short te17222) {
        this.te17222 = te17222;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17223
     *
     * @return the value of TE17.TE17223
     *
     * @mbggenerated
     */
    public Short getTe17223() {
        return te17223;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17223
     *
     * @param te17223 the value for TE17.TE17223
     *
     * @mbggenerated
     */
    public void setTe17223(Short te17223) {
        this.te17223 = te17223;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17224
     *
     * @return the value of TE17.TE17224
     *
     * @mbggenerated
     */
    public Short getTe17224() {
        return te17224;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17224
     *
     * @param te17224 the value for TE17.TE17224
     *
     * @mbggenerated
     */
    public void setTe17224(Short te17224) {
        this.te17224 = te17224;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17225
     *
     * @return the value of TE17.TE17225
     *
     * @mbggenerated
     */
    public Short getTe17225() {
        return te17225;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17225
     *
     * @param te17225 the value for TE17.TE17225
     *
     * @mbggenerated
     */
    public void setTe17225(Short te17225) {
        this.te17225 = te17225;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17226
     *
     * @return the value of TE17.TE17226
     *
     * @mbggenerated
     */
    public Short getTe17226() {
        return te17226;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17226
     *
     * @param te17226 the value for TE17.TE17226
     *
     * @mbggenerated
     */
    public void setTe17226(Short te17226) {
        this.te17226 = te17226;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17227
     *
     * @return the value of TE17.TE17227
     *
     * @mbggenerated
     */
    public Short getTe17227() {
        return te17227;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17227
     *
     * @param te17227 the value for TE17.TE17227
     *
     * @mbggenerated
     */
    public void setTe17227(Short te17227) {
        this.te17227 = te17227;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17228
     *
     * @return the value of TE17.TE17228
     *
     * @mbggenerated
     */
    public Short getTe17228() {
        return te17228;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17228
     *
     * @param te17228 the value for TE17.TE17228
     *
     * @mbggenerated
     */
    public void setTe17228(Short te17228) {
        this.te17228 = te17228;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17229
     *
     * @return the value of TE17.TE17229
     *
     * @mbggenerated
     */
    public Short getTe17229() {
        return te17229;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17229
     *
     * @param te17229 the value for TE17.TE17229
     *
     * @mbggenerated
     */
    public void setTe17229(Short te17229) {
        this.te17229 = te17229;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17230
     *
     * @return the value of TE17.TE17230
     *
     * @mbggenerated
     */
    public Short getTe17230() {
        return te17230;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17230
     *
     * @param te17230 the value for TE17.TE17230
     *
     * @mbggenerated
     */
    public void setTe17230(Short te17230) {
        this.te17230 = te17230;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17301
     *
     * @return the value of TE17.TE17301
     *
     * @mbggenerated
     */
    public String getTe17301() {
        return te17301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17301
     *
     * @param te17301 the value for TE17.TE17301
     *
     * @mbggenerated
     */
    public void setTe17301(String te17301) {
        this.te17301 = te17301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17302
     *
     * @return the value of TE17.TE17302
     *
     * @mbggenerated
     */
    public String getTe17302() {
        return te17302;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17302
     *
     * @param te17302 the value for TE17.TE17302
     *
     * @mbggenerated
     */
    public void setTe17302(String te17302) {
        this.te17302 = te17302;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17303
     *
     * @return the value of TE17.TE17303
     *
     * @mbggenerated
     */
    public String getTe17303() {
        return te17303;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17303
     *
     * @param te17303 the value for TE17.TE17303
     *
     * @mbggenerated
     */
    public void setTe17303(String te17303) {
        this.te17303 = te17303;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17304
     *
     * @return the value of TE17.TE17304
     *
     * @mbggenerated
     */
    public String getTe17304() {
        return te17304;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17304
     *
     * @param te17304 the value for TE17.TE17304
     *
     * @mbggenerated
     */
    public void setTe17304(String te17304) {
        this.te17304 = te17304;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17305
     *
     * @return the value of TE17.TE17305
     *
     * @mbggenerated
     */
    public String getTe17305() {
        return te17305;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17305
     *
     * @param te17305 the value for TE17.TE17305
     *
     * @mbggenerated
     */
    public void setTe17305(String te17305) {
        this.te17305 = te17305;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.TE17306
     *
     * @return the value of TE17.TE17306
     *
     * @mbggenerated
     */
    public String getTe17306() {
        return te17306;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.TE17306
     *
     * @param te17306 the value for TE17.TE17306
     *
     * @mbggenerated
     */
    public void setTe17306(String te17306) {
        this.te17306 = te17306;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.CREATOR
     *
     * @return the value of TE17.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.CREATOR
     *
     * @param creator the value for TE17.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.CREATE_TIMESTAMP
     *
     * @return the value of TE17.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE17.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.UPDATER
     *
     * @return the value of TE17.UPDATER
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.UPDATER
     *
     * @param updater the value for TE17.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.UPDATE_TIMESTAMP
     *
     * @return the value of TE17.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE17.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.UPDATE_APP
     *
     * @return the value of TE17.UPDATE_APP
     *
     * @mbggenerated
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.UPDATE_APP
     *
     * @param updateApp the value for TE17.UPDATE_APP
     *
     * @mbggenerated
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE17.VERSION_NO
     *
     * @return the value of TE17.VERSION_NO
     *
     * @mbggenerated
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE17.VERSION_NO
     *
     * @param versionNo the value for TE17.VERSION_NO
     *
     * @mbggenerated
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}