package com.common.dao.model;

public class Te73Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73001
     *
     * @mbggenerated
     */
    private String te73001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE73.TE73002
     *
     * @mbggenerated
     */
    private Integer te73002;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73001
     *
     * @return the value of TE73.TE73001
     *
     * @mbggenerated
     */
    public String getTe73001() {
        return te73001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73001
     *
     * @param te73001 the value for TE73.TE73001
     *
     * @mbggenerated
     */
    public void setTe73001(String te73001) {
        this.te73001 = te73001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE73.TE73002
     *
     * @return the value of TE73.TE73002
     *
     * @mbggenerated
     */
    public Integer getTe73002() {
        return te73002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE73.TE73002
     *
     * @param te73002 the value for TE73.TE73002
     *
     * @mbggenerated
     */
    public void setTe73002(Integer te73002) {
        this.te73002 = te73002;
    }
}