package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te76 extends Te76Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76101
     *
     * @mbggenerated
     */
    private String te76101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76102
     *
     * @mbggenerated
     */
    private BigDecimal te76102;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76201
     *
     * @mbggenerated
     */
    private String te76201;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76202
     *
     * @mbggenerated
     */
    private String te76202;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76203
     *
     * @mbggenerated
     */
    private String te76203;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76204
     *
     * @mbggenerated
     */
    private String te76204;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76205
     *
     * @mbggenerated
     */
    private String te76205;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76206
     *
     * @mbggenerated
     */
    private String te76206;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76207
     *
     * @mbggenerated
     */
    private String te76207;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76208
     *
     * @mbggenerated
     */
    private String te76208;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76209
     *
     * @mbggenerated
     */
    private String te76209;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76210
     *
     * @mbggenerated
     */
    private String te76210;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76211
     *
     * @mbggenerated
     */
    private String te76211;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76212
     *
     * @mbggenerated
     */
    private String te76212;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76213
     *
     * @mbggenerated
     */
    private String te76213;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76214
     *
     * @mbggenerated
     */
    private String te76214;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76215
     *
     * @mbggenerated
     */
    private String te76215;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76216
     *
     * @mbggenerated
     */
    private String te76216;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76217
     *
     * @mbggenerated
     */
    private String te76217;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76218
     *
     * @mbggenerated
     */
    private String te76218;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76219
     *
     * @mbggenerated
     */
    private String te76219;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76220
     *
     * @mbggenerated
     */
    private String te76220;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76221
     *
     * @mbggenerated
     */
    private String te76221;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76222
     *
     * @mbggenerated
     */
    private String te76222;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76223
     *
     * @mbggenerated
     */
    private String te76223;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76224
     *
     * @mbggenerated
     */
    private String te76224;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.UPDATER
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.UPDATE_APP
     *
     * @mbggenerated
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.VERSION_NO
     *
     * @mbggenerated
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76101
     *
     * @return the value of TE76.TE76101
     *
     * @mbggenerated
     */
    public String getTe76101() {
        return te76101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76101
     *
     * @param te76101 the value for TE76.TE76101
     *
     * @mbggenerated
     */
    public void setTe76101(String te76101) {
        this.te76101 = te76101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76102
     *
     * @return the value of TE76.TE76102
     *
     * @mbggenerated
     */
    public BigDecimal getTe76102() {
        return te76102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76102
     *
     * @param te76102 the value for TE76.TE76102
     *
     * @mbggenerated
     */
    public void setTe76102(BigDecimal te76102) {
        this.te76102 = te76102;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76201
     *
     * @return the value of TE76.TE76201
     *
     * @mbggenerated
     */
    public String getTe76201() {
        return te76201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76201
     *
     * @param te76201 the value for TE76.TE76201
     *
     * @mbggenerated
     */
    public void setTe76201(String te76201) {
        this.te76201 = te76201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76202
     *
     * @return the value of TE76.TE76202
     *
     * @mbggenerated
     */
    public String getTe76202() {
        return te76202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76202
     *
     * @param te76202 the value for TE76.TE76202
     *
     * @mbggenerated
     */
    public void setTe76202(String te76202) {
        this.te76202 = te76202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76203
     *
     * @return the value of TE76.TE76203
     *
     * @mbggenerated
     */
    public String getTe76203() {
        return te76203;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76203
     *
     * @param te76203 the value for TE76.TE76203
     *
     * @mbggenerated
     */
    public void setTe76203(String te76203) {
        this.te76203 = te76203;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76204
     *
     * @return the value of TE76.TE76204
     *
     * @mbggenerated
     */
    public String getTe76204() {
        return te76204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76204
     *
     * @param te76204 the value for TE76.TE76204
     *
     * @mbggenerated
     */
    public void setTe76204(String te76204) {
        this.te76204 = te76204;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76205
     *
     * @return the value of TE76.TE76205
     *
     * @mbggenerated
     */
    public String getTe76205() {
        return te76205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76205
     *
     * @param te76205 the value for TE76.TE76205
     *
     * @mbggenerated
     */
    public void setTe76205(String te76205) {
        this.te76205 = te76205;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76206
     *
     * @return the value of TE76.TE76206
     *
     * @mbggenerated
     */
    public String getTe76206() {
        return te76206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76206
     *
     * @param te76206 the value for TE76.TE76206
     *
     * @mbggenerated
     */
    public void setTe76206(String te76206) {
        this.te76206 = te76206;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76207
     *
     * @return the value of TE76.TE76207
     *
     * @mbggenerated
     */
    public String getTe76207() {
        return te76207;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76207
     *
     * @param te76207 the value for TE76.TE76207
     *
     * @mbggenerated
     */
    public void setTe76207(String te76207) {
        this.te76207 = te76207;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76208
     *
     * @return the value of TE76.TE76208
     *
     * @mbggenerated
     */
    public String getTe76208() {
        return te76208;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76208
     *
     * @param te76208 the value for TE76.TE76208
     *
     * @mbggenerated
     */
    public void setTe76208(String te76208) {
        this.te76208 = te76208;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76209
     *
     * @return the value of TE76.TE76209
     *
     * @mbggenerated
     */
    public String getTe76209() {
        return te76209;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76209
     *
     * @param te76209 the value for TE76.TE76209
     *
     * @mbggenerated
     */
    public void setTe76209(String te76209) {
        this.te76209 = te76209;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76210
     *
     * @return the value of TE76.TE76210
     *
     * @mbggenerated
     */
    public String getTe76210() {
        return te76210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76210
     *
     * @param te76210 the value for TE76.TE76210
     *
     * @mbggenerated
     */
    public void setTe76210(String te76210) {
        this.te76210 = te76210;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76211
     *
     * @return the value of TE76.TE76211
     *
     * @mbggenerated
     */
    public String getTe76211() {
        return te76211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76211
     *
     * @param te76211 the value for TE76.TE76211
     *
     * @mbggenerated
     */
    public void setTe76211(String te76211) {
        this.te76211 = te76211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76212
     *
     * @return the value of TE76.TE76212
     *
     * @mbggenerated
     */
    public String getTe76212() {
        return te76212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76212
     *
     * @param te76212 the value for TE76.TE76212
     *
     * @mbggenerated
     */
    public void setTe76212(String te76212) {
        this.te76212 = te76212;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76213
     *
     * @return the value of TE76.TE76213
     *
     * @mbggenerated
     */
    public String getTe76213() {
        return te76213;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76213
     *
     * @param te76213 the value for TE76.TE76213
     *
     * @mbggenerated
     */
    public void setTe76213(String te76213) {
        this.te76213 = te76213;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76214
     *
     * @return the value of TE76.TE76214
     *
     * @mbggenerated
     */
    public String getTe76214() {
        return te76214;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76214
     *
     * @param te76214 the value for TE76.TE76214
     *
     * @mbggenerated
     */
    public void setTe76214(String te76214) {
        this.te76214 = te76214;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76215
     *
     * @return the value of TE76.TE76215
     *
     * @mbggenerated
     */
    public String getTe76215() {
        return te76215;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76215
     *
     * @param te76215 the value for TE76.TE76215
     *
     * @mbggenerated
     */
    public void setTe76215(String te76215) {
        this.te76215 = te76215;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76216
     *
     * @return the value of TE76.TE76216
     *
     * @mbggenerated
     */
    public String getTe76216() {
        return te76216;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76216
     *
     * @param te76216 the value for TE76.TE76216
     *
     * @mbggenerated
     */
    public void setTe76216(String te76216) {
        this.te76216 = te76216;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76217
     *
     * @return the value of TE76.TE76217
     *
     * @mbggenerated
     */
    public String getTe76217() {
        return te76217;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76217
     *
     * @param te76217 the value for TE76.TE76217
     *
     * @mbggenerated
     */
    public void setTe76217(String te76217) {
        this.te76217 = te76217;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76218
     *
     * @return the value of TE76.TE76218
     *
     * @mbggenerated
     */
    public String getTe76218() {
        return te76218;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76218
     *
     * @param te76218 the value for TE76.TE76218
     *
     * @mbggenerated
     */
    public void setTe76218(String te76218) {
        this.te76218 = te76218;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76219
     *
     * @return the value of TE76.TE76219
     *
     * @mbggenerated
     */
    public String getTe76219() {
        return te76219;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76219
     *
     * @param te76219 the value for TE76.TE76219
     *
     * @mbggenerated
     */
    public void setTe76219(String te76219) {
        this.te76219 = te76219;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76220
     *
     * @return the value of TE76.TE76220
     *
     * @mbggenerated
     */
    public String getTe76220() {
        return te76220;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76220
     *
     * @param te76220 the value for TE76.TE76220
     *
     * @mbggenerated
     */
    public void setTe76220(String te76220) {
        this.te76220 = te76220;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76221
     *
     * @return the value of TE76.TE76221
     *
     * @mbggenerated
     */
    public String getTe76221() {
        return te76221;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76221
     *
     * @param te76221 the value for TE76.TE76221
     *
     * @mbggenerated
     */
    public void setTe76221(String te76221) {
        this.te76221 = te76221;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76222
     *
     * @return the value of TE76.TE76222
     *
     * @mbggenerated
     */
    public String getTe76222() {
        return te76222;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76222
     *
     * @param te76222 the value for TE76.TE76222
     *
     * @mbggenerated
     */
    public void setTe76222(String te76222) {
        this.te76222 = te76222;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76223
     *
     * @return the value of TE76.TE76223
     *
     * @mbggenerated
     */
    public String getTe76223() {
        return te76223;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76223
     *
     * @param te76223 the value for TE76.TE76223
     *
     * @mbggenerated
     */
    public void setTe76223(String te76223) {
        this.te76223 = te76223;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76224
     *
     * @return the value of TE76.TE76224
     *
     * @mbggenerated
     */
    public String getTe76224() {
        return te76224;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76224
     *
     * @param te76224 the value for TE76.TE76224
     *
     * @mbggenerated
     */
    public void setTe76224(String te76224) {
        this.te76224 = te76224;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.CREATOR
     *
     * @return the value of TE76.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.CREATOR
     *
     * @param creator the value for TE76.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.CREATE_TIMESTAMP
     *
     * @return the value of TE76.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE76.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.UPDATER
     *
     * @return the value of TE76.UPDATER
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.UPDATER
     *
     * @param updater the value for TE76.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.UPDATE_TIMESTAMP
     *
     * @return the value of TE76.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE76.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.UPDATE_APP
     *
     * @return the value of TE76.UPDATE_APP
     *
     * @mbggenerated
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.UPDATE_APP
     *
     * @param updateApp the value for TE76.UPDATE_APP
     *
     * @mbggenerated
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.VERSION_NO
     *
     * @return the value of TE76.VERSION_NO
     *
     * @mbggenerated
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.VERSION_NO
     *
     * @param versionNo the value for TE76.VERSION_NO
     *
     * @mbggenerated
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}