package com.common.dao.model;

import java.math.BigDecimal;

public class Te76Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private String te76001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE76.TE76002
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    private BigDecimal te76002;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76001
     *
     * @return the value of TE76.TE76001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public String getTe76001() {
        return te76001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76001
     *
     * @param te76001 the value for TE76.TE76001
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe76001(String te76001) {
        this.te76001 = te76001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE76.TE76002
     *
     * @return the value of TE76.TE76002
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public BigDecimal getTe76002() {
        return te76002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE76.TE76002
     *
     * @param te76002 the value for TE76.TE76002
     *
     * @mbggenerated Sat May 21 21:52:31 JST 2016
     */
    public void setTe76002(BigDecimal te76002) {
        this.te76002 = te76002;
    }
}