package com.common.dao.model;

import java.math.BigDecimal;

public class Te79Key {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE79.TE79001
     *
     * @mbggenerated
     */
    private String te79001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE79.TE79002
     *
     * @mbggenerated
     */
    private BigDecimal te79002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE79.TE79003
     *
     * @mbggenerated
     */
    private Short te79003;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE79.TE79001
     *
     * @return the value of TE79.TE79001
     *
     * @mbggenerated
     */
    public String getTe79001() {
        return te79001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE79.TE79001
     *
     * @param te79001 the value for TE79.TE79001
     *
     * @mbggenerated
     */
    public void setTe79001(String te79001) {
        this.te79001 = te79001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE79.TE79002
     *
     * @return the value of TE79.TE79002
     *
     * @mbggenerated
     */
    public BigDecimal getTe79002() {
        return te79002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE79.TE79002
     *
     * @param te79002 the value for TE79.TE79002
     *
     * @mbggenerated
     */
    public void setTe79002(BigDecimal te79002) {
        this.te79002 = te79002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE79.TE79003
     *
     * @return the value of TE79.TE79003
     *
     * @mbggenerated
     */
    public Short getTe79003() {
        return te79003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE79.TE79003
     *
     * @param te79003 the value for TE79.TE79003
     *
     * @mbggenerated
     */
    public void setTe79003(Short te79003) {
        this.te79003 = te79003;
    }
}