package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te7a extends Te7aKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.TE7A101
     *
     * @mbggenerated
     */
    private String te7a101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.UPDATER
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.UPDATE_APP
     *
     * @mbggenerated
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7A.VERSION_NO
     *
     * @mbggenerated
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.TE7A101
     *
     * @return the value of TE7A.TE7A101
     *
     * @mbggenerated
     */
    public String getTe7a101() {
        return te7a101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.TE7A101
     *
     * @param te7a101 the value for TE7A.TE7A101
     *
     * @mbggenerated
     */
    public void setTe7a101(String te7a101) {
        this.te7a101 = te7a101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.CREATOR
     *
     * @return the value of TE7A.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.CREATOR
     *
     * @param creator the value for TE7A.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.CREATE_TIMESTAMP
     *
     * @return the value of TE7A.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE7A.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.UPDATER
     *
     * @return the value of TE7A.UPDATER
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.UPDATER
     *
     * @param updater the value for TE7A.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.UPDATE_TIMESTAMP
     *
     * @return the value of TE7A.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE7A.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.UPDATE_APP
     *
     * @return the value of TE7A.UPDATE_APP
     *
     * @mbggenerated
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.UPDATE_APP
     *
     * @param updateApp the value for TE7A.UPDATE_APP
     *
     * @mbggenerated
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7A.VERSION_NO
     *
     * @return the value of TE7A.VERSION_NO
     *
     * @mbggenerated
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7A.VERSION_NO
     *
     * @param versionNo the value for TE7A.VERSION_NO
     *
     * @mbggenerated
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}