package com.common.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Te7aExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public Te7aExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTe7a001IsNull() {
            addCriterion("TE7A001 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a001IsNotNull() {
            addCriterion("TE7A001 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a001EqualTo(String value) {
            addCriterion("TE7A001 =", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001NotEqualTo(String value) {
            addCriterion("TE7A001 <>", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001GreaterThan(String value) {
            addCriterion("TE7A001 >", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001GreaterThanOrEqualTo(String value) {
            addCriterion("TE7A001 >=", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001LessThan(String value) {
            addCriterion("TE7A001 <", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001LessThanOrEqualTo(String value) {
            addCriterion("TE7A001 <=", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001Like(String value) {
            addCriterion("TE7A001 like", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001NotLike(String value) {
            addCriterion("TE7A001 not like", value, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001In(List<String> values) {
            addCriterion("TE7A001 in", values, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001NotIn(List<String> values) {
            addCriterion("TE7A001 not in", values, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001Between(String value1, String value2) {
            addCriterion("TE7A001 between", value1, value2, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a001NotBetween(String value1, String value2) {
            addCriterion("TE7A001 not between", value1, value2, "te7a001");
            return (Criteria) this;
        }

        public Criteria andTe7a002IsNull() {
            addCriterion("TE7A002 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a002IsNotNull() {
            addCriterion("TE7A002 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a002EqualTo(BigDecimal value) {
            addCriterion("TE7A002 =", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002NotEqualTo(BigDecimal value) {
            addCriterion("TE7A002 <>", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002GreaterThan(BigDecimal value) {
            addCriterion("TE7A002 >", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TE7A002 >=", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002LessThan(BigDecimal value) {
            addCriterion("TE7A002 <", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002LessThanOrEqualTo(BigDecimal value) {
            addCriterion("TE7A002 <=", value, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002In(List<BigDecimal> values) {
            addCriterion("TE7A002 in", values, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002NotIn(List<BigDecimal> values) {
            addCriterion("TE7A002 not in", values, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE7A002 between", value1, value2, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a002NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE7A002 not between", value1, value2, "te7a002");
            return (Criteria) this;
        }

        public Criteria andTe7a003IsNull() {
            addCriterion("TE7A003 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a003IsNotNull() {
            addCriterion("TE7A003 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a003EqualTo(Short value) {
            addCriterion("TE7A003 =", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003NotEqualTo(Short value) {
            addCriterion("TE7A003 <>", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003GreaterThan(Short value) {
            addCriterion("TE7A003 >", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003GreaterThanOrEqualTo(Short value) {
            addCriterion("TE7A003 >=", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003LessThan(Short value) {
            addCriterion("TE7A003 <", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003LessThanOrEqualTo(Short value) {
            addCriterion("TE7A003 <=", value, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003In(List<Short> values) {
            addCriterion("TE7A003 in", values, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003NotIn(List<Short> values) {
            addCriterion("TE7A003 not in", values, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003Between(Short value1, Short value2) {
            addCriterion("TE7A003 between", value1, value2, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a003NotBetween(Short value1, Short value2) {
            addCriterion("TE7A003 not between", value1, value2, "te7a003");
            return (Criteria) this;
        }

        public Criteria andTe7a004IsNull() {
            addCriterion("TE7A004 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a004IsNotNull() {
            addCriterion("TE7A004 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a004EqualTo(Short value) {
            addCriterion("TE7A004 =", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004NotEqualTo(Short value) {
            addCriterion("TE7A004 <>", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004GreaterThan(Short value) {
            addCriterion("TE7A004 >", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004GreaterThanOrEqualTo(Short value) {
            addCriterion("TE7A004 >=", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004LessThan(Short value) {
            addCriterion("TE7A004 <", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004LessThanOrEqualTo(Short value) {
            addCriterion("TE7A004 <=", value, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004In(List<Short> values) {
            addCriterion("TE7A004 in", values, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004NotIn(List<Short> values) {
            addCriterion("TE7A004 not in", values, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004Between(Short value1, Short value2) {
            addCriterion("TE7A004 between", value1, value2, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a004NotBetween(Short value1, Short value2) {
            addCriterion("TE7A004 not between", value1, value2, "te7a004");
            return (Criteria) this;
        }

        public Criteria andTe7a005IsNull() {
            addCriterion("TE7A005 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a005IsNotNull() {
            addCriterion("TE7A005 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a005EqualTo(String value) {
            addCriterion("TE7A005 =", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005NotEqualTo(String value) {
            addCriterion("TE7A005 <>", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005GreaterThan(String value) {
            addCriterion("TE7A005 >", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005GreaterThanOrEqualTo(String value) {
            addCriterion("TE7A005 >=", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005LessThan(String value) {
            addCriterion("TE7A005 <", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005LessThanOrEqualTo(String value) {
            addCriterion("TE7A005 <=", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005Like(String value) {
            addCriterion("TE7A005 like", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005NotLike(String value) {
            addCriterion("TE7A005 not like", value, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005In(List<String> values) {
            addCriterion("TE7A005 in", values, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005NotIn(List<String> values) {
            addCriterion("TE7A005 not in", values, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005Between(String value1, String value2) {
            addCriterion("TE7A005 between", value1, value2, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a005NotBetween(String value1, String value2) {
            addCriterion("TE7A005 not between", value1, value2, "te7a005");
            return (Criteria) this;
        }

        public Criteria andTe7a101IsNull() {
            addCriterion("TE7A101 is null");
            return (Criteria) this;
        }

        public Criteria andTe7a101IsNotNull() {
            addCriterion("TE7A101 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7a101EqualTo(String value) {
            addCriterion("TE7A101 =", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101NotEqualTo(String value) {
            addCriterion("TE7A101 <>", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101GreaterThan(String value) {
            addCriterion("TE7A101 >", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101GreaterThanOrEqualTo(String value) {
            addCriterion("TE7A101 >=", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101LessThan(String value) {
            addCriterion("TE7A101 <", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101LessThanOrEqualTo(String value) {
            addCriterion("TE7A101 <=", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101Like(String value) {
            addCriterion("TE7A101 like", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101NotLike(String value) {
            addCriterion("TE7A101 not like", value, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101In(List<String> values) {
            addCriterion("TE7A101 in", values, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101NotIn(List<String> values) {
            addCriterion("TE7A101 not in", values, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101Between(String value1, String value2) {
            addCriterion("TE7A101 between", value1, value2, "te7a101");
            return (Criteria) this;
        }

        public Criteria andTe7a101NotBetween(String value1, String value2) {
            addCriterion("TE7A101 not between", value1, value2, "te7a101");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("UPDATE_APP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("UPDATE_APP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("UPDATE_APP =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("UPDATE_APP <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("UPDATE_APP >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("UPDATE_APP <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("UPDATE_APP like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("UPDATE_APP not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("UPDATE_APP in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("UPDATE_APP not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("UPDATE_APP between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("UPDATE_APP not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("VERSION_NO is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("VERSION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(BigDecimal value) {
            addCriterion("VERSION_NO >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(BigDecimal value) {
            addCriterion("VERSION_NO <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO not between", value1, value2, "versionNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7A
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7A
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}