package com.common.dao.model;

import java.math.BigDecimal;

public class Te7bKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7B.TE7B001
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    private String te7b001;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7B.TE7B002
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    private BigDecimal te7b002;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7B.TE7B003
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    private Short te7b003;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7B.TE7B004
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    private Short te7b004;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7B.TE7B001
     *
     * @return the value of TE7B.TE7B001
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public String getTe7b001() {
        return te7b001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7B.TE7B001
     *
     * @param te7b001 the value for TE7B.TE7B001
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public void setTe7b001(String te7b001) {
        this.te7b001 = te7b001;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7B.TE7B002
     *
     * @return the value of TE7B.TE7B002
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public BigDecimal getTe7b002() {
        return te7b002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7B.TE7B002
     *
     * @param te7b002 the value for TE7B.TE7B002
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public void setTe7b002(BigDecimal te7b002) {
        this.te7b002 = te7b002;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7B.TE7B003
     *
     * @return the value of TE7B.TE7B003
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public Short getTe7b003() {
        return te7b003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7B.TE7B003
     *
     * @param te7b003 the value for TE7B.TE7B003
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public void setTe7b003(Short te7b003) {
        this.te7b003 = te7b003;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7B.TE7B004
     *
     * @return the value of TE7B.TE7B004
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public Short getTe7b004() {
        return te7b004;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7B.TE7B004
     *
     * @param te7b004 the value for TE7B.TE7B004
     *
     * @mbggenerated Sun May 22 09:43:50 JST 2016
     */
    public void setTe7b004(Short te7b004) {
        this.te7b004 = te7b004;
    }
}