package com.common.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Te7bExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public Te7bExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTe7b001IsNull() {
            addCriterion("TE7B001 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b001IsNotNull() {
            addCriterion("TE7B001 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b001EqualTo(String value) {
            addCriterion("TE7B001 =", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001NotEqualTo(String value) {
            addCriterion("TE7B001 <>", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001GreaterThan(String value) {
            addCriterion("TE7B001 >", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001GreaterThanOrEqualTo(String value) {
            addCriterion("TE7B001 >=", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001LessThan(String value) {
            addCriterion("TE7B001 <", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001LessThanOrEqualTo(String value) {
            addCriterion("TE7B001 <=", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001Like(String value) {
            addCriterion("TE7B001 like", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001NotLike(String value) {
            addCriterion("TE7B001 not like", value, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001In(List<String> values) {
            addCriterion("TE7B001 in", values, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001NotIn(List<String> values) {
            addCriterion("TE7B001 not in", values, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001Between(String value1, String value2) {
            addCriterion("TE7B001 between", value1, value2, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b001NotBetween(String value1, String value2) {
            addCriterion("TE7B001 not between", value1, value2, "te7b001");
            return (Criteria) this;
        }

        public Criteria andTe7b002IsNull() {
            addCriterion("TE7B002 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b002IsNotNull() {
            addCriterion("TE7B002 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b002EqualTo(BigDecimal value) {
            addCriterion("TE7B002 =", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002NotEqualTo(BigDecimal value) {
            addCriterion("TE7B002 <>", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002GreaterThan(BigDecimal value) {
            addCriterion("TE7B002 >", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TE7B002 >=", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002LessThan(BigDecimal value) {
            addCriterion("TE7B002 <", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002LessThanOrEqualTo(BigDecimal value) {
            addCriterion("TE7B002 <=", value, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002In(List<BigDecimal> values) {
            addCriterion("TE7B002 in", values, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002NotIn(List<BigDecimal> values) {
            addCriterion("TE7B002 not in", values, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE7B002 between", value1, value2, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b002NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TE7B002 not between", value1, value2, "te7b002");
            return (Criteria) this;
        }

        public Criteria andTe7b003IsNull() {
            addCriterion("TE7B003 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b003IsNotNull() {
            addCriterion("TE7B003 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b003EqualTo(Short value) {
            addCriterion("TE7B003 =", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003NotEqualTo(Short value) {
            addCriterion("TE7B003 <>", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003GreaterThan(Short value) {
            addCriterion("TE7B003 >", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003GreaterThanOrEqualTo(Short value) {
            addCriterion("TE7B003 >=", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003LessThan(Short value) {
            addCriterion("TE7B003 <", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003LessThanOrEqualTo(Short value) {
            addCriterion("TE7B003 <=", value, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003In(List<Short> values) {
            addCriterion("TE7B003 in", values, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003NotIn(List<Short> values) {
            addCriterion("TE7B003 not in", values, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003Between(Short value1, Short value2) {
            addCriterion("TE7B003 between", value1, value2, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b003NotBetween(Short value1, Short value2) {
            addCriterion("TE7B003 not between", value1, value2, "te7b003");
            return (Criteria) this;
        }

        public Criteria andTe7b004IsNull() {
            addCriterion("TE7B004 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b004IsNotNull() {
            addCriterion("TE7B004 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b004EqualTo(Short value) {
            addCriterion("TE7B004 =", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004NotEqualTo(Short value) {
            addCriterion("TE7B004 <>", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004GreaterThan(Short value) {
            addCriterion("TE7B004 >", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004GreaterThanOrEqualTo(Short value) {
            addCriterion("TE7B004 >=", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004LessThan(Short value) {
            addCriterion("TE7B004 <", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004LessThanOrEqualTo(Short value) {
            addCriterion("TE7B004 <=", value, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004In(List<Short> values) {
            addCriterion("TE7B004 in", values, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004NotIn(List<Short> values) {
            addCriterion("TE7B004 not in", values, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004Between(Short value1, Short value2) {
            addCriterion("TE7B004 between", value1, value2, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b004NotBetween(Short value1, Short value2) {
            addCriterion("TE7B004 not between", value1, value2, "te7b004");
            return (Criteria) this;
        }

        public Criteria andTe7b101IsNull() {
            addCriterion("TE7B101 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b101IsNotNull() {
            addCriterion("TE7B101 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b101EqualTo(String value) {
            addCriterion("TE7B101 =", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101NotEqualTo(String value) {
            addCriterion("TE7B101 <>", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101GreaterThan(String value) {
            addCriterion("TE7B101 >", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101GreaterThanOrEqualTo(String value) {
            addCriterion("TE7B101 >=", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101LessThan(String value) {
            addCriterion("TE7B101 <", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101LessThanOrEqualTo(String value) {
            addCriterion("TE7B101 <=", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101Like(String value) {
            addCriterion("TE7B101 like", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101NotLike(String value) {
            addCriterion("TE7B101 not like", value, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101In(List<String> values) {
            addCriterion("TE7B101 in", values, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101NotIn(List<String> values) {
            addCriterion("TE7B101 not in", values, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101Between(String value1, String value2) {
            addCriterion("TE7B101 between", value1, value2, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b101NotBetween(String value1, String value2) {
            addCriterion("TE7B101 not between", value1, value2, "te7b101");
            return (Criteria) this;
        }

        public Criteria andTe7b102IsNull() {
            addCriterion("TE7B102 is null");
            return (Criteria) this;
        }

        public Criteria andTe7b102IsNotNull() {
            addCriterion("TE7B102 is not null");
            return (Criteria) this;
        }

        public Criteria andTe7b102EqualTo(String value) {
            addCriterion("TE7B102 =", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102NotEqualTo(String value) {
            addCriterion("TE7B102 <>", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102GreaterThan(String value) {
            addCriterion("TE7B102 >", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102GreaterThanOrEqualTo(String value) {
            addCriterion("TE7B102 >=", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102LessThan(String value) {
            addCriterion("TE7B102 <", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102LessThanOrEqualTo(String value) {
            addCriterion("TE7B102 <=", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102Like(String value) {
            addCriterion("TE7B102 like", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102NotLike(String value) {
            addCriterion("TE7B102 not like", value, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102In(List<String> values) {
            addCriterion("TE7B102 in", values, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102NotIn(List<String> values) {
            addCriterion("TE7B102 not in", values, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102Between(String value1, String value2) {
            addCriterion("TE7B102 between", value1, value2, "te7b102");
            return (Criteria) this;
        }

        public Criteria andTe7b102NotBetween(String value1, String value2) {
            addCriterion("TE7B102 not between", value1, value2, "te7b102");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("UPDATE_APP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("UPDATE_APP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("UPDATE_APP =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("UPDATE_APP <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("UPDATE_APP >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("UPDATE_APP <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("UPDATE_APP like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("UPDATE_APP not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("UPDATE_APP in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("UPDATE_APP not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("UPDATE_APP between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("UPDATE_APP not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("VERSION_NO is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("VERSION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(BigDecimal value) {
            addCriterion("VERSION_NO >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(BigDecimal value) {
            addCriterion("VERSION_NO <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO not between", value1, value2, "versionNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7B
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TE7B
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}