package com.common.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Te7j extends Te7jKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J101
     *
     * @mbggenerated
     */
    private String te7j101;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J201
     *
     * @mbggenerated
     */
    private String te7j201;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J202
     *
     * @mbggenerated
     */
    private BigDecimal te7j202;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J301
     *
     * @mbggenerated
     */
    private String te7j301;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J401
     *
     * @mbggenerated
     */
    private String te7j401;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J402
     *
     * @mbggenerated
     */
    private String te7j402;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J403
     *
     * @mbggenerated
     */
    private String te7j403;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.TE7J501
     *
     * @mbggenerated
     */
    private String te7j501;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.UPDATER
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.UPDATE_APP
     *
     * @mbggenerated
     */
    private String updateApp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TE7J.VERSION_NO
     *
     * @mbggenerated
     */
    private BigDecimal versionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J101
     *
     * @return the value of TE7J.TE7J101
     *
     * @mbggenerated
     */
    public String getTe7j101() {
        return te7j101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J101
     *
     * @param te7j101 the value for TE7J.TE7J101
     *
     * @mbggenerated
     */
    public void setTe7j101(String te7j101) {
        this.te7j101 = te7j101;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J201
     *
     * @return the value of TE7J.TE7J201
     *
     * @mbggenerated
     */
    public String getTe7j201() {
        return te7j201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J201
     *
     * @param te7j201 the value for TE7J.TE7J201
     *
     * @mbggenerated
     */
    public void setTe7j201(String te7j201) {
        this.te7j201 = te7j201;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J202
     *
     * @return the value of TE7J.TE7J202
     *
     * @mbggenerated
     */
    public BigDecimal getTe7j202() {
        return te7j202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J202
     *
     * @param te7j202 the value for TE7J.TE7J202
     *
     * @mbggenerated
     */
    public void setTe7j202(BigDecimal te7j202) {
        this.te7j202 = te7j202;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J301
     *
     * @return the value of TE7J.TE7J301
     *
     * @mbggenerated
     */
    public String getTe7j301() {
        return te7j301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J301
     *
     * @param te7j301 the value for TE7J.TE7J301
     *
     * @mbggenerated
     */
    public void setTe7j301(String te7j301) {
        this.te7j301 = te7j301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J401
     *
     * @return the value of TE7J.TE7J401
     *
     * @mbggenerated
     */
    public String getTe7j401() {
        return te7j401;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J401
     *
     * @param te7j401 the value for TE7J.TE7J401
     *
     * @mbggenerated
     */
    public void setTe7j401(String te7j401) {
        this.te7j401 = te7j401;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J402
     *
     * @return the value of TE7J.TE7J402
     *
     * @mbggenerated
     */
    public String getTe7j402() {
        return te7j402;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J402
     *
     * @param te7j402 the value for TE7J.TE7J402
     *
     * @mbggenerated
     */
    public void setTe7j402(String te7j402) {
        this.te7j402 = te7j402;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J403
     *
     * @return the value of TE7J.TE7J403
     *
     * @mbggenerated
     */
    public String getTe7j403() {
        return te7j403;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J403
     *
     * @param te7j403 the value for TE7J.TE7J403
     *
     * @mbggenerated
     */
    public void setTe7j403(String te7j403) {
        this.te7j403 = te7j403;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.TE7J501
     *
     * @return the value of TE7J.TE7J501
     *
     * @mbggenerated
     */
    public String getTe7j501() {
        return te7j501;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.TE7J501
     *
     * @param te7j501 the value for TE7J.TE7J501
     *
     * @mbggenerated
     */
    public void setTe7j501(String te7j501) {
        this.te7j501 = te7j501;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.CREATOR
     *
     * @return the value of TE7J.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.CREATOR
     *
     * @param creator the value for TE7J.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.CREATE_TIMESTAMP
     *
     * @return the value of TE7J.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.CREATE_TIMESTAMP
     *
     * @param createTimestamp the value for TE7J.CREATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.UPDATER
     *
     * @return the value of TE7J.UPDATER
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.UPDATER
     *
     * @param updater the value for TE7J.UPDATER
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.UPDATE_TIMESTAMP
     *
     * @return the value of TE7J.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for TE7J.UPDATE_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.UPDATE_APP
     *
     * @return the value of TE7J.UPDATE_APP
     *
     * @mbggenerated
     */
    public String getUpdateApp() {
        return updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.UPDATE_APP
     *
     * @param updateApp the value for TE7J.UPDATE_APP
     *
     * @mbggenerated
     */
    public void setUpdateApp(String updateApp) {
        this.updateApp = updateApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TE7J.VERSION_NO
     *
     * @return the value of TE7J.VERSION_NO
     *
     * @mbggenerated
     */
    public BigDecimal getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TE7J.VERSION_NO
     *
     * @param versionNo the value for TE7J.VERSION_NO
     *
     * @mbggenerated
     */
    public void setVersionNo(BigDecimal versionNo) {
        this.versionNo = versionNo;
    }
}