package com.common.dao.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Tpe7Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public Tpe7Example() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTpe7001IsNull() {
            addCriterion("TPE7001 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7001IsNotNull() {
            addCriterion("TPE7001 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7001EqualTo(String value) {
            addCriterion("TPE7001 =", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001NotEqualTo(String value) {
            addCriterion("TPE7001 <>", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001GreaterThan(String value) {
            addCriterion("TPE7001 >", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7001 >=", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001LessThan(String value) {
            addCriterion("TPE7001 <", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001LessThanOrEqualTo(String value) {
            addCriterion("TPE7001 <=", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001Like(String value) {
            addCriterion("TPE7001 like", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001NotLike(String value) {
            addCriterion("TPE7001 not like", value, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001In(List<String> values) {
            addCriterion("TPE7001 in", values, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001NotIn(List<String> values) {
            addCriterion("TPE7001 not in", values, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001Between(String value1, String value2) {
            addCriterion("TPE7001 between", value1, value2, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7001NotBetween(String value1, String value2) {
            addCriterion("TPE7001 not between", value1, value2, "tpe7001");
            return (Criteria) this;
        }

        public Criteria andTpe7002IsNull() {
            addCriterion("TPE7002 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7002IsNotNull() {
            addCriterion("TPE7002 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7002EqualTo(String value) {
            addCriterion("TPE7002 =", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002NotEqualTo(String value) {
            addCriterion("TPE7002 <>", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002GreaterThan(String value) {
            addCriterion("TPE7002 >", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7002 >=", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002LessThan(String value) {
            addCriterion("TPE7002 <", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002LessThanOrEqualTo(String value) {
            addCriterion("TPE7002 <=", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002Like(String value) {
            addCriterion("TPE7002 like", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002NotLike(String value) {
            addCriterion("TPE7002 not like", value, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002In(List<String> values) {
            addCriterion("TPE7002 in", values, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002NotIn(List<String> values) {
            addCriterion("TPE7002 not in", values, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002Between(String value1, String value2) {
            addCriterion("TPE7002 between", value1, value2, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7002NotBetween(String value1, String value2) {
            addCriterion("TPE7002 not between", value1, value2, "tpe7002");
            return (Criteria) this;
        }

        public Criteria andTpe7003IsNull() {
            addCriterion("TPE7003 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7003IsNotNull() {
            addCriterion("TPE7003 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7003EqualTo(String value) {
            addCriterion("TPE7003 =", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003NotEqualTo(String value) {
            addCriterion("TPE7003 <>", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003GreaterThan(String value) {
            addCriterion("TPE7003 >", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7003 >=", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003LessThan(String value) {
            addCriterion("TPE7003 <", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003LessThanOrEqualTo(String value) {
            addCriterion("TPE7003 <=", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003Like(String value) {
            addCriterion("TPE7003 like", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003NotLike(String value) {
            addCriterion("TPE7003 not like", value, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003In(List<String> values) {
            addCriterion("TPE7003 in", values, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003NotIn(List<String> values) {
            addCriterion("TPE7003 not in", values, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003Between(String value1, String value2) {
            addCriterion("TPE7003 between", value1, value2, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7003NotBetween(String value1, String value2) {
            addCriterion("TPE7003 not between", value1, value2, "tpe7003");
            return (Criteria) this;
        }

        public Criteria andTpe7004IsNull() {
            addCriterion("TPE7004 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7004IsNotNull() {
            addCriterion("TPE7004 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7004EqualTo(String value) {
            addCriterion("TPE7004 =", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004NotEqualTo(String value) {
            addCriterion("TPE7004 <>", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004GreaterThan(String value) {
            addCriterion("TPE7004 >", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7004 >=", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004LessThan(String value) {
            addCriterion("TPE7004 <", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004LessThanOrEqualTo(String value) {
            addCriterion("TPE7004 <=", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004Like(String value) {
            addCriterion("TPE7004 like", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004NotLike(String value) {
            addCriterion("TPE7004 not like", value, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004In(List<String> values) {
            addCriterion("TPE7004 in", values, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004NotIn(List<String> values) {
            addCriterion("TPE7004 not in", values, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004Between(String value1, String value2) {
            addCriterion("TPE7004 between", value1, value2, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7004NotBetween(String value1, String value2) {
            addCriterion("TPE7004 not between", value1, value2, "tpe7004");
            return (Criteria) this;
        }

        public Criteria andTpe7005IsNull() {
            addCriterion("TPE7005 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7005IsNotNull() {
            addCriterion("TPE7005 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7005EqualTo(Short value) {
            addCriterion("TPE7005 =", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005NotEqualTo(Short value) {
            addCriterion("TPE7005 <>", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005GreaterThan(Short value) {
            addCriterion("TPE7005 >", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005GreaterThanOrEqualTo(Short value) {
            addCriterion("TPE7005 >=", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005LessThan(Short value) {
            addCriterion("TPE7005 <", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005LessThanOrEqualTo(Short value) {
            addCriterion("TPE7005 <=", value, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005In(List<Short> values) {
            addCriterion("TPE7005 in", values, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005NotIn(List<Short> values) {
            addCriterion("TPE7005 not in", values, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005Between(Short value1, Short value2) {
            addCriterion("TPE7005 between", value1, value2, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7005NotBetween(Short value1, Short value2) {
            addCriterion("TPE7005 not between", value1, value2, "tpe7005");
            return (Criteria) this;
        }

        public Criteria andTpe7101IsNull() {
            addCriterion("TPE7101 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7101IsNotNull() {
            addCriterion("TPE7101 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7101EqualTo(String value) {
            addCriterion("TPE7101 =", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101NotEqualTo(String value) {
            addCriterion("TPE7101 <>", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101GreaterThan(String value) {
            addCriterion("TPE7101 >", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7101 >=", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101LessThan(String value) {
            addCriterion("TPE7101 <", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101LessThanOrEqualTo(String value) {
            addCriterion("TPE7101 <=", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101Like(String value) {
            addCriterion("TPE7101 like", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101NotLike(String value) {
            addCriterion("TPE7101 not like", value, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101In(List<String> values) {
            addCriterion("TPE7101 in", values, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101NotIn(List<String> values) {
            addCriterion("TPE7101 not in", values, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101Between(String value1, String value2) {
            addCriterion("TPE7101 between", value1, value2, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7101NotBetween(String value1, String value2) {
            addCriterion("TPE7101 not between", value1, value2, "tpe7101");
            return (Criteria) this;
        }

        public Criteria andTpe7102IsNull() {
            addCriterion("TPE7102 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7102IsNotNull() {
            addCriterion("TPE7102 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7102EqualTo(String value) {
            addCriterion("TPE7102 =", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102NotEqualTo(String value) {
            addCriterion("TPE7102 <>", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102GreaterThan(String value) {
            addCriterion("TPE7102 >", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7102 >=", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102LessThan(String value) {
            addCriterion("TPE7102 <", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102LessThanOrEqualTo(String value) {
            addCriterion("TPE7102 <=", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102Like(String value) {
            addCriterion("TPE7102 like", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102NotLike(String value) {
            addCriterion("TPE7102 not like", value, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102In(List<String> values) {
            addCriterion("TPE7102 in", values, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102NotIn(List<String> values) {
            addCriterion("TPE7102 not in", values, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102Between(String value1, String value2) {
            addCriterion("TPE7102 between", value1, value2, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7102NotBetween(String value1, String value2) {
            addCriterion("TPE7102 not between", value1, value2, "tpe7102");
            return (Criteria) this;
        }

        public Criteria andTpe7103IsNull() {
            addCriterion("TPE7103 is null");
            return (Criteria) this;
        }

        public Criteria andTpe7103IsNotNull() {
            addCriterion("TPE7103 is not null");
            return (Criteria) this;
        }

        public Criteria andTpe7103EqualTo(String value) {
            addCriterion("TPE7103 =", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103NotEqualTo(String value) {
            addCriterion("TPE7103 <>", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103GreaterThan(String value) {
            addCriterion("TPE7103 >", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103GreaterThanOrEqualTo(String value) {
            addCriterion("TPE7103 >=", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103LessThan(String value) {
            addCriterion("TPE7103 <", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103LessThanOrEqualTo(String value) {
            addCriterion("TPE7103 <=", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103Like(String value) {
            addCriterion("TPE7103 like", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103NotLike(String value) {
            addCriterion("TPE7103 not like", value, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103In(List<String> values) {
            addCriterion("TPE7103 in", values, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103NotIn(List<String> values) {
            addCriterion("TPE7103 not in", values, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103Between(String value1, String value2) {
            addCriterion("TPE7103 between", value1, value2, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andTpe7103NotBetween(String value1, String value2) {
            addCriterion("TPE7103 not between", value1, value2, "tpe7103");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNull() {
            addCriterion("CREATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIsNotNull() {
            addCriterion("CREATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP =", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <>", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThan(Date value) {
            addCriterion("CREATE_TIMESTAMP >", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP >=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThan(Date value) {
            addCriterion("CREATE_TIMESTAMP <", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIMESTAMP <=", value, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotIn(List<Date> values) {
            addCriterion("CREATE_TIMESTAMP not in", values, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andCreateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIMESTAMP not between", value1, value2, "createTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("UPDATER is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("UPDATER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(String value) {
            addCriterion("UPDATER =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(String value) {
            addCriterion("UPDATER <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(String value) {
            addCriterion("UPDATER >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATER >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(String value) {
            addCriterion("UPDATER <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(String value) {
            addCriterion("UPDATER <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLike(String value) {
            addCriterion("UPDATER like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotLike(String value) {
            addCriterion("UPDATER not like", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<String> values) {
            addCriterion("UPDATER in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<String> values) {
            addCriterion("UPDATER not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(String value1, String value2) {
            addCriterion("UPDATER between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(String value1, String value2) {
            addCriterion("UPDATER not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("UPDATE_TIMESTAMP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("UPDATE_TIMESTAMP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("UPDATE_TIMESTAMP <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIMESTAMP <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("UPDATE_TIMESTAMP not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIMESTAMP not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNull() {
            addCriterion("UPDATE_APP is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIsNotNull() {
            addCriterion("UPDATE_APP is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAppEqualTo(String value) {
            addCriterion("UPDATE_APP =", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotEqualTo(String value) {
            addCriterion("UPDATE_APP <>", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThan(String value) {
            addCriterion("UPDATE_APP >", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP >=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThan(String value) {
            addCriterion("UPDATE_APP <", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_APP <=", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppLike(String value) {
            addCriterion("UPDATE_APP like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotLike(String value) {
            addCriterion("UPDATE_APP not like", value, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppIn(List<String> values) {
            addCriterion("UPDATE_APP in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotIn(List<String> values) {
            addCriterion("UPDATE_APP not in", values, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppBetween(String value1, String value2) {
            addCriterion("UPDATE_APP between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andUpdateAppNotBetween(String value1, String value2) {
            addCriterion("UPDATE_APP not between", value1, value2, "updateApp");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("VERSION_NO is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("VERSION_NO is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(BigDecimal value) {
            addCriterion("VERSION_NO >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(BigDecimal value) {
            addCriterion("VERSION_NO <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERSION_NO <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<BigDecimal> values) {
            addCriterion("VERSION_NO not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERSION_NO not between", value1, value2, "versionNo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TPE7
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TPE7
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}