package net.newbiz.ebil.system.dao.model;

import java.util.Date;

public class MSysUserGroup extends MSysUserGroupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.sys_state_cd
     *
     * @mbggenerated
     */
    private Short sysStateCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.creater
     *
     * @mbggenerated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.create_timestamp
     *
     * @mbggenerated
     */
    private Date createTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.updater
     *
     * @mbggenerated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.update_timestamp
     *
     * @mbggenerated
     */
    private Date updateTimestamp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.sys_state_cd
     *
     * @return the value of m_sys_user_group.sys_state_cd
     *
     * @mbggenerated
     */
    public Short getSysStateCd() {
        return sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.sys_state_cd
     *
     * @param sysStateCd the value for m_sys_user_group.sys_state_cd
     *
     * @mbggenerated
     */
    public void setSysStateCd(Short sysStateCd) {
        this.sysStateCd = sysStateCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.creater
     *
     * @return the value of m_sys_user_group.creater
     *
     * @mbggenerated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.creater
     *
     * @param creater the value for m_sys_user_group.creater
     *
     * @mbggenerated
     */
    public void setCreater(String creater) {
        this.creater = creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.create_timestamp
     *
     * @return the value of m_sys_user_group.create_timestamp
     *
     * @mbggenerated
     */
    public Date getCreateTimestamp() {
        return createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.create_timestamp
     *
     * @param createTimestamp the value for m_sys_user_group.create_timestamp
     *
     * @mbggenerated
     */
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.updater
     *
     * @return the value of m_sys_user_group.updater
     *
     * @mbggenerated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.updater
     *
     * @param updater the value for m_sys_user_group.updater
     *
     * @mbggenerated
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.update_timestamp
     *
     * @return the value of m_sys_user_group.update_timestamp
     *
     * @mbggenerated
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.update_timestamp
     *
     * @param updateTimestamp the value for m_sys_user_group.update_timestamp
     *
     * @mbggenerated
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}