package net.newbiz.ebil.system.dao.model;

public class MSysUserGroupKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.sys_user_id
     *
     * @mbggenerated
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_user_group.sys_group_id
     *
     * @mbggenerated
     */
    private String sysGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.sys_user_id
     *
     * @return the value of m_sys_user_group.sys_user_id
     *
     * @mbggenerated
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.sys_user_id
     *
     * @param sysUserId the value for m_sys_user_group.sys_user_id
     *
     * @mbggenerated
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_user_group.sys_group_id
     *
     * @return the value of m_sys_user_group.sys_group_id
     *
     * @mbggenerated
     */
    public String getSysGroupId() {
        return sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_user_group.sys_group_id
     *
     * @param sysGroupId the value for m_sys_user_group.sys_group_id
     *
     * @mbggenerated
     */
    public void setSysGroupId(String sysGroupId) {
        this.sysGroupId = sysGroupId;
    }
}