package net.newbiz.ebil.system.dao.model;

public class MSysGroupRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_group_role.sys_group_id
     *
     * @mbggenerated
     */
    private String sysGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_group_role.sys_role_id
     *
     * @mbggenerated
     */
    private Short sysRoleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_group_role.sys_group_id
     *
     * @return the value of m_sys_group_role.sys_group_id
     *
     * @mbggenerated
     */
    public String getSysGroupId() {
        return sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_group_role.sys_group_id
     *
     * @param sysGroupId the value for m_sys_group_role.sys_group_id
     *
     * @mbggenerated
     */
    public void setSysGroupId(String sysGroupId) {
        this.sysGroupId = sysGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_group_role.sys_role_id
     *
     * @return the value of m_sys_group_role.sys_role_id
     *
     * @mbggenerated
     */
    public Short getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_group_role.sys_role_id
     *
     * @param sysRoleId the value for m_sys_group_role.sys_role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(Short sysRoleId) {
        this.sysRoleId = sysRoleId;
    }
}