package net.newbiz.ebil.system.dao.model;

public class MSysRoleAuthorityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_role_authority.sys_role_id
     *
     * @mbggenerated
     */
    private Short sysRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_sys_role_authority.sys_authority_id
     *
     * @mbggenerated
     */
    private Short sysAuthorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_role_authority.sys_role_id
     *
     * @return the value of m_sys_role_authority.sys_role_id
     *
     * @mbggenerated
     */
    public Short getSysRoleId() {
        return sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_role_authority.sys_role_id
     *
     * @param sysRoleId the value for m_sys_role_authority.sys_role_id
     *
     * @mbggenerated
     */
    public void setSysRoleId(Short sysRoleId) {
        this.sysRoleId = sysRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_sys_role_authority.sys_authority_id
     *
     * @return the value of m_sys_role_authority.sys_authority_id
     *
     * @mbggenerated
     */
    public Short getSysAuthorityId() {
        return sysAuthorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_sys_role_authority.sys_authority_id
     *
     * @param sysAuthorityId the value for m_sys_role_authority.sys_authority_id
     *
     * @mbggenerated
     */
    public void setSysAuthorityId(Short sysAuthorityId) {
        this.sysAuthorityId = sysAuthorityId;
    }
}